// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * text?: string // Text
 * link?: string // Link
 * newTab?: boolean // New Tab
}} Props

 */
import { stdin_default } from "../chunks/chunk-GP3RWMYO.js";
import { className, css, fonts } from "../chunks/chunk-DRXSNPA2.js";
import { routes } from "../chunks/chunk-643FN7SQ.js";

// virtual:button/arrow-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qkId8TaqANsRl7Ve9sYQ/2ngohlXpl9LE4bqhAQwB/vEs04sOvc.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ArrowDropdownCaretSortSelectArrowFonts = getFonts(stdin_default);
var enabledGestures = {
	paPdF5fA4: {
		hover: true,
	},
};
var serializationHash = "framer-jfbI3";
var variantClassNames = {
	paPdF5fA4: "framer-v-1e0m8dk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, link, newTab, text, width, ...props }) => {
	return {
		...props,
		k35iLgODE: text ?? props.k35iLgODE ?? "support@ametrix.com",
		OMNs9Kt50: newTab ?? props.OMNs9Kt50,
		tib4PO9YV: link ?? props.tib4PO9YV,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		k35iLgODE: k35iLgODE2,
		tib4PO9YV: tib4PO9YV2,
		OMNs9Kt50: OMNs9Kt502,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "paPdF5fA4",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={tib4PO9YV2}
						motionChild={true}
						nodeId={"paPdF5fA4"}
						openInNewTab={OMNs9Kt502}
						scopeId={"vEs04sOvc"}
						smoothScroll={true}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1e0m8dk", className2, classNames)} framer-bj3ba0`}
							data-framer-name={"Default"}
							layoutDependency={layoutDependency}
							layoutId={"paPdF5fA4"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"paPdF5fA4-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-14zqrkc"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"hL62f1rPQ"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-9ff70694-0783-4e61-9f6a-7b939313b3bd, rgb(38, 38, 38))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={k35iLgODE2}
								variants={{
									"paPdF5fA4-hover": {
										"--extracted-r6o4lv":
											"var(--token-421e20c4-0040-4023-a28d-103276930f09, rgb(77, 77, 77))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"paPdF5fA4-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1dqim52"}
														data-styles-preset={"QowBsUafH"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-421e20c4-0040-4023-a28d-103276930f09, rgb(77, 77, 77)))",
														}}
													>
														{"support@ametrix.com"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1dqim52"}
										data-styles-preset={"QowBsUafH"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-9ff70694-0783-4e61-9f6a-7b939313b3bd, rgb(38, 38, 38)))",
										}}
									>
										{"support@ametrix.com"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-1cudv88"}
								data-framer-name={"Icon Container"}
								layoutDependency={layoutDependency}
								layoutId={"wMm8CRKyW"}
							>
								{_jsx(stdin_default, {
									animated: true,
									className: "framer-1xuzq9h",
									layoutDependency,
									layoutId: "xaPP_sNen",
									style: {
										"--1ww558a": 2,
										"--4rxgx6":
											"var(--token-9ff70694-0783-4e61-9f6a-7b939313b3bd, rgb(38, 38, 38))",
										rotate: -90,
									},
									transformTemplate: transformTemplate1,
									...addPropertyOverrides(
										{
											"paPdF5fA4-hover": {
												transformTemplate: transformTemplate2,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
								{_jsx(stdin_default, {
									animated: true,
									className: "framer-1jmzlyb",
									layoutDependency,
									layoutId: "ohSP9hfrJ",
									style: {
										"--1ww558a": 2,
										"--4rxgx6":
											"var(--token-9ff70694-0783-4e61-9f6a-7b939313b3bd, rgb(38, 38, 38))",
										rotate: -90,
									},
									transformTemplate: transformTemplate2,
									...addPropertyOverrides(
										{
											"paPdF5fA4-hover": {
												transformTemplate: transformTemplate1,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-jfbI3.framer-bj3ba0, .framer-jfbI3 .framer-bj3ba0 { display: block; }",
	".framer-jfbI3.framer-1e0m8dk { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-jfbI3 .framer-14zqrkc { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-jfbI3 .framer-1cudv88 { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 22px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 22px; }",
	".framer-jfbI3 .framer-1xuzq9h { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 23px); left: -24px; position: absolute; top: 50%; width: 23px; z-index: 1; }",
	".framer-jfbI3 .framer-1jmzlyb { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 23px); left: 50%; position: absolute; top: 50%; width: 23px; z-index: 1; }",
	".framer-jfbI3.framer-v-1e0m8dk.hover .framer-1xuzq9h { left: 50%; }",
	".framer-jfbI3.framer-v-1e0m8dk.hover .framer-1jmzlyb { left: 24px; }",
	...css,
];
var FramervEs04sOvc = withCSS(Component, css2, "framer-jfbI3");
var stdin_default2 = FramervEs04sOvc;
FramervEs04sOvc.displayName = "Button/Arrow Button";
FramervEs04sOvc.defaultProps = {
	height: 22.5,
	width: 164.5,
};
addPropertyControls(FramervEs04sOvc, {
	k35iLgODE: {
		defaultValue: "support@ametrix.com",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	tib4PO9YV: {
		title: "Link",
		type: ControlType.Link,
	},
	OMNs9Kt50: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramervEs04sOvc,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ArrowDropdownCaretSortSelectArrowFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button/arrow-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ArrowButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var arrow_button_default = ComponentWithRoot;
export { arrow_button_default as default };
