// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Dark' | 'Orange' | 'Light' | 'Light-Back' | 'Dark-Back' | 'Light-2' // Variant
 * link?: string // Link
 * newTab?: boolean // New Tab
 * text?: string // Text
 * padding?: undefined // Padding
 * iconVisible?: boolean // Icon Visible
 * click?: Function // Click
 * bGColor?: string // BG Color
}} Props

 */
import { stdin_default } from "../chunks/chunk-XAVSUTR4.js";
import "../chunks/chunk-GP3RWMYO.js";
import "../chunks/chunk-DRXSNPA2.js";
import { routes } from "../chunks/chunk-643FN7SQ.js";

// virtual:button/primary-button
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "HE9WL3Va9",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PrimaryButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var primary_button_default = ComponentWithRoot;
export { primary_button_default as default };
