// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * icon?: undefined // Icon
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-DRXSNPA2.js";
import { routes } from "../chunks/chunk-643FN7SQ.js";

// virtual:button/secondary-social-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/5luwPnukIVEslj6yUmEt/YhP5mQa3r00AOKrjcpnz/qco40gm2Q.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFontsFromSharedStyle,
	Instance,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/461JU8PGnDWvtaNPV7wG/OLgekpS1DC3aXLeOdeDy/Kymq9IoZM.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 18.002 1.643 C 16.927 0.625 15.096 0.001 13.502 0.001 C 12.139 -0.003 10.816 0.461 9.752 1.313 L 9.752 1.313 C 8.711 0.478 7.419 0.016 6.085 0.001 C 2.627 -0.046 -0.086 2.841 0.002 6.3 C 0.078 9.294 1.349 12.134 3.532 14.186 C 4.088 14.71 4.825 15.002 5.59 15.001 L 13.811 15.001 C 14.637 15.004 15.427 14.664 15.992 14.063 C 17.478 12.469 18.002 10.951 18.002 10.951 L 18.002 10.951 C 16.428 9.87 15.752 8.057 15.752 6.002 C 15.752 4.287 16.847 2.739 18.002 1.645 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="15.000587682821056px" id="sfViky700" transform="translate(2.248 5.249)" width="18.002087329641306px"/><path d="M 18.002 1.643 C 16.927 0.625 15.096 0.001 13.502 0.001 C 12.139 -0.003 10.816 0.461 9.752 1.313 L 9.752 1.313 C 8.711 0.478 7.419 0.016 6.085 0.001 C 2.627 -0.046 -0.086 2.841 0.002 6.3 C 0.078 9.294 1.349 12.134 3.532 14.186 C 4.088 14.71 4.825 15.002 5.59 15.001 L 13.811 15.001 C 14.637 15.004 15.427 14.664 15.992 14.063 C 17.478 12.469 18.002 10.951 18.002 10.951 L 18.002 10.951 C 16.428 9.87 15.752 8.057 15.752 6.002 C 15.752 4.287 16.847 2.739 18.002 1.645 Z" fill="transparent" height="15.000587682821056px" id="x1tCHhctS" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(2.248 5.249)" width="18.002087329641306px"/><path d="M 3 0 L 2.906 0 C 1.538 -0.001 0.342 0.925 0 2.25" fill="transparent" height="2.2500003854452766px" id="n_CkzrPwl" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(12.75 0.75)" width="3px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("485495485", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-AlRRS", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css2 = [
	`.framer-AlRRS { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css2, "framer-AlRRS");
Icon.displayName = "Apple Logo";
var stdin_default = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/5luwPnukIVEslj6yUmEt/YhP5mQa3r00AOKrjcpnz/qco40gm2Q.js
var enabledGestures = {
	dPcOJT4Ok: {
		hover: true,
	},
};
var serializationHash = "framer-vFGIk";
var variantClassNames = {
	dPcOJT4Ok: "framer-v-5hmi1x",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var getProps2 = ({ height, icon, id, link, width, ...props }) => {
	return {
		...props,
		EV311Sjvo: icon ?? props.EV311Sjvo ?? stdin_default,
		Z62DKxb7W: link ?? props.Z62DKxb7W,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		EV311Sjvo: EV311Sjvo2,
		Z62DKxb7W: Z62DKxb7W2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "dPcOJT4Ok",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={Z62DKxb7W2}
						motionChild={true}
						nodeId={"dPcOJT4Ok"}
						openInNewTab={true}
						scopeId={"qco40gm2Q"}
					>
						<motion2.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx2(scopingClassNames, "framer-5hmi1x", className2, classNames)} framer-9nqws5`}
							data-border={true}
							data-framer-name={"Default"}
							layoutDependency={layoutDependency}
							layoutId={"dPcOJT4Ok"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(255, 255, 255, 0.15)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgba(255, 255, 255, 0.1)",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								...style,
							}}
							variants={{
								"dPcOJT4Ok-hover": {
									"--border-color": "rgba(255, 255, 255, 0)",
									backgroundColor: "rgba(255, 255, 255, 0.24)",
								},
							}}
							{...addPropertyOverrides(
								{
									"dPcOJT4Ok-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-11123md"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"iFW500NEl"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"center"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-1dqim52"}
										data-styles-preset={"QowBsUafH"}
									>
										{"Download for"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<Instance
								animated={true}
								className={"framer-1dr9um9"}
								Component={EV311Sjvo2}
								layoutDependency={layoutDependency}
								layoutId={"Kk0uLKhtC"}
								style={{
									"--1m6trwb": 1,
									"--21h8s6":
										"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
									"--pgex8v": 1.5,
								}}
							/>
						</motion2.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-vFGIk.framer-9nqws5, .framer-vFGIk .framer-9nqws5 { display: block; }",
	".framer-vFGIk.framer-5hmi1x { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 10px 16px 10px 18px; position: relative; text-decoration: none; width: min-content; }",
	".framer-vFGIk .framer-11123md { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-vFGIk .framer-1dr9um9 { flex: none; height: var(--framer-aspect-ratio-supported, 22px); position: relative; width: 22px; }",
	...css,
	'.framer-vFGIk[data-border="true"]::after, .framer-vFGIk [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Framerqco40gm2Q = withCSS2(Component2, css3, "framer-vFGIk");
var stdin_default2 = Framerqco40gm2Q;
Framerqco40gm2Q.displayName = "Button/Secondary Social Button";
Framerqco40gm2Q.defaultProps = {
	height: 42.5,
	width: 148.5,
};
addPropertyControls2(Framerqco40gm2Q, {
	EV311Sjvo: {
		defaultValue: {
			identifier:
				"module:461JU8PGnDWvtaNPV7wG/OLgekpS1DC3aXLeOdeDy/Kymq9IoZM.js:default",
			moduleId: "461JU8PGnDWvtaNPV7wG",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon",
		type: ControlType2.VectorSetItem,
	},
	Z62DKxb7W: {
		title: "Link",
		type: ControlType2.Link,
	},
});
addFonts(
	Framerqco40gm2Q,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button/secondary-social-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SecondarySocialButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var secondary_social_button_default = ComponentWithRoot;
export { secondary_social_button_default as default };
