// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default as stdin_default3 } from "../chunks/chunk-NW7LP6IH.js";
import { stdin_default } from "../chunks/chunk-6KOE3X73.js";
import { className, css, fonts } from "../chunks/chunk-QGLA3TUC.js";
import { stdin_default as stdin_default2 } from "../chunks/chunk-Z6E5IQ3K.js";
import "../chunks/chunk-GP3RWMYO.js";
import "../chunks/chunk-DRXSNPA2.js";
import { routes } from "../chunks/chunk-643FN7SQ.js";

// virtual:helper/cta
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3HdKE7qUG7AkiCHY3tDN/wI0IpGVHs1ImlEmB77Rk/sgDJdh8KT.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/WX1Ui22jnyJ4iHtUiS1S/gwxm6iqFtqoUsmt3zYiL/Rr_znKXnP.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Inter Tight-600",
	"GF;Inter Tight-900",
	"GF;Inter Tight-900italic",
	"GF;Inter Tight-600italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Inter Tight",
				source: "google",
				style: "normal",
				uiFamilyName: "Inter Tight",
				url: "https://fonts.gstatic.com/s/intertight/v9/NGSnv5HMAFg6IuGlBNMjxJEL2VmU3NS7Z2mj0QiqWSRToK8EPg.woff2",
				weight: "600",
			},
			{
				cssFamilyName: "Inter Tight",
				source: "google",
				style: "normal",
				uiFamilyName: "Inter Tight",
				url: "https://fonts.gstatic.com/s/intertight/v9/NGSnv5HMAFg6IuGlBNMjxJEL2VmU3NS7Z2mjpgiqWSRToK8EPg.woff2",
				weight: "900",
			},
			{
				cssFamilyName: "Inter Tight",
				source: "google",
				style: "italic",
				uiFamilyName: "Inter Tight",
				url: "https://fonts.gstatic.com/s/intertight/v9/NGShv5HMAFg6IuGlBNMjxLsC66ZMtb8hyW62x0zrGC5SgqoUPvi5.woff2",
				weight: "900",
			},
			{
				cssFamilyName: "Inter Tight",
				source: "google",
				style: "italic",
				uiFamilyName: "Inter Tight",
				url: "https://fonts.gstatic.com/s/intertight/v9/NGShv5HMAFg6IuGlBNMjxLsC66ZMtb8hyW62x0ycGC5SgqoUPvi5.woff2",
				weight: "600",
			},
		],
	},
];
var css2 = [
	'.framer-MFpzL .framer-styles-preset-i6x10:not(.rich-text-wrapper), .framer-MFpzL .framer-styles-preset-i6x10.rich-text-wrapper h1 { --framer-font-family: "Inter Tight", "Inter Tight Placeholder", sans-serif; --framer-font-family-bold: "Inter Tight", sans-serif; --framer-font-family-bold-italic: "Inter Tight", sans-serif; --framer-font-family-italic: "Inter Tight", "Inter Tight Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 50px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.02em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-aa15e029-4bb1-434e-9852-151a8d809557, #1a1a1a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-MFpzL .framer-styles-preset-i6x10:not(.rich-text-wrapper), .framer-MFpzL .framer-styles-preset-i6x10.rich-text-wrapper h1 { --framer-font-family: "Inter Tight", "Inter Tight Placeholder", sans-serif; --framer-font-family-bold: "Inter Tight", sans-serif; --framer-font-family-bold-italic: "Inter Tight", sans-serif; --framer-font-family-italic: "Inter Tight", "Inter Tight Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 46px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.02em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-aa15e029-4bb1-434e-9852-151a8d809557, #1a1a1a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-MFpzL .framer-styles-preset-i6x10:not(.rich-text-wrapper), .framer-MFpzL .framer-styles-preset-i6x10.rich-text-wrapper h1 { --framer-font-family: "Inter Tight", "Inter Tight Placeholder", sans-serif; --framer-font-family-bold: "Inter Tight", sans-serif; --framer-font-family-bold-italic: "Inter Tight", sans-serif; --framer-font-family-italic: "Inter Tight", "Inter Tight Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 38px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.02em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-aa15e029-4bb1-434e-9852-151a8d809557, #1a1a1a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-MFpzL";

// /:https://framerusercontent.com/modules/3HdKE7qUG7AkiCHY3tDN/wI0IpGVHs1ImlEmB77Rk/sgDJdh8KT.js
var ButtonPrimaryButtonFonts = getFonts(stdin_default2);
var ButtonSecondaryButtonFonts = getFonts(stdin_default3);
var cycleOrder = ["NJJqXtw1K", "tZjPsgXIP", "vyndh9pQD"];
var serializationHash = "framer-rbe9H";
var variantClassNames = {
	NJJqXtw1K: "framer-v-1dlajkh",
	tZjPsgXIP: "framer-v-nmn60l",
	vyndh9pQD: "framer-v-1k5cmzq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "NJJqXtw1K",
	Phone: "vyndh9pQD",
	Tablet: "tZjPsgXIP",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "NJJqXtw1K",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NJJqXtw1K",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "vyndh9pQD") return false;
		return true;
	};
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1dlajkh",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"NJJqXtw1K"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								tZjPsgXIP: {
									"data-framer-name": "Tablet",
								},
								vyndh9pQD: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-188fyus"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"l10J2WH3T"}
							style={{
								backgroundColor:
									"var(--token-9847b0ae-2e9c-4d9e-a90d-c710abb2638b, rgb(13, 13, 13))",
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						>
							{isDisplayed() && (
								<Image
									as={"figure"}
									background={{
										alt: "Left Abstract",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 486.5) - 0 - 690) / 2 +
													0 +
													0) +
												0,
										),
										pixelHeight: 1936,
										pixelWidth: 2324,
										positionX: "left",
										positionY: "center",
										sizes: "310px",
										src: "https://framerusercontent.com/images/HRMUWELf7kJYqEkRN3V5Gm1Pk8.png?width=2324&height=1936",
										srcSet:
											"https://framerusercontent.com/images/HRMUWELf7kJYqEkRN3V5Gm1Pk8.png?scale-down-to=512&width=2324&height=1936 512w,https://framerusercontent.com/images/HRMUWELf7kJYqEkRN3V5Gm1Pk8.png?scale-down-to=1024&width=2324&height=1936 1024w,https://framerusercontent.com/images/HRMUWELf7kJYqEkRN3V5Gm1Pk8.png?scale-down-to=2048&width=2324&height=1936 2048w,https://framerusercontent.com/images/HRMUWELf7kJYqEkRN3V5Gm1Pk8.png?width=2324&height=1936 2324w",
									}}
									className={"framer-ssldkb"}
									data-framer-name={"Left Abstract"}
									layoutDependency={layoutDependency}
									layoutId={"jdy8oNMdE"}
								/>
							)}
							{isDisplayed() && (
								<Image
									as={"figure"}
									background={{
										alt: "Right Abstract",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 486.5) - 0 - 690) / 2 +
													0 +
													0) +
												0,
										),
										pixelHeight: 1936,
										pixelWidth: 2324,
										positionX: "right",
										positionY: "center",
										sizes: "310px",
										src: "https://framerusercontent.com/images/NTnule69X1FmxYE7AwmFliAASY.png?width=2324&height=1936",
										srcSet:
											"https://framerusercontent.com/images/NTnule69X1FmxYE7AwmFliAASY.png?scale-down-to=512&width=2324&height=1936 512w,https://framerusercontent.com/images/NTnule69X1FmxYE7AwmFliAASY.png?scale-down-to=1024&width=2324&height=1936 1024w,https://framerusercontent.com/images/NTnule69X1FmxYE7AwmFliAASY.png?scale-down-to=2048&width=2324&height=1936 2048w,https://framerusercontent.com/images/NTnule69X1FmxYE7AwmFliAASY.png?width=2324&height=1936 2324w",
									}}
									className={"framer-m8nv21"}
									data-framer-name={"Right Abstract"}
									layoutDependency={layoutDependency}
									layoutId={"T2YYtm9jr"}
								/>
							)}
							<Image
								as={"figure"}
								background={{
									alt: "Top Abstract",
									fit: "fill",
									intrinsicHeight: 352,
									intrinsicWidth: 1420,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 486.5) - 0 - 690) / 2 +
												0 +
												0) +
											0,
									),
									pixelHeight: 352,
									pixelWidth: 1420,
									sizes: `calc(${componentViewport?.width || "100vw"} - 40px)`,
									src: "https://framerusercontent.com/images/zHpW1QjTIQQHoJUXBGwIVusNE.svg?width=1420&height=352",
									srcSet:
										"https://framerusercontent.com/images/zHpW1QjTIQQHoJUXBGwIVusNE.svg?scale-down-to=512&width=1420&height=352 512w,https://framerusercontent.com/images/zHpW1QjTIQQHoJUXBGwIVusNE.svg?scale-down-to=1024&width=1420&height=352 1024w,https://framerusercontent.com/images/zHpW1QjTIQQHoJUXBGwIVusNE.svg?width=1420&height=352 1420w",
								}}
								className={"framer-zskf40"}
								data-framer-name={"Abstract"}
								layoutDependency={layoutDependency}
								layoutId={"lk5wro3ON"}
								{...addPropertyOverrides(
									{
										vyndh9pQD: {
											background: {
												alt: "Top Abstract",
												fit: "fill",
												intrinsicHeight: 352,
												intrinsicWidth: 1420,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 559) - 0 - 574.5) /
															2 +
															0 +
															0) +
														0,
												),
												pixelHeight: 352,
												pixelWidth: 1420,
												sizes: `calc(${componentViewport?.width || "100vw"} - 20px)`,
												src: "https://framerusercontent.com/images/zHpW1QjTIQQHoJUXBGwIVusNE.svg?width=1420&height=352",
												srcSet:
													"https://framerusercontent.com/images/zHpW1QjTIQQHoJUXBGwIVusNE.svg?scale-down-to=512&width=1420&height=352 512w,https://framerusercontent.com/images/zHpW1QjTIQQHoJUXBGwIVusNE.svg?scale-down-to=1024&width=1420&height=352 1024w,https://framerusercontent.com/images/zHpW1QjTIQQHoJUXBGwIVusNE.svg?width=1420&height=352 1420w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<Image
								as={"figure"}
								background={{
									alt: "Top Patch",
									fit: "fill",
									intrinsicHeight: 1987.5,
									intrinsicWidth: 2130,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 486.5) - 0 - 690) / 2 +
												0 +
												0) +
											0,
									),
									pixelHeight: 3975,
									pixelWidth: 4260,
									sizes: `calc(${componentViewport?.width || "100vw"} - 40px)`,
									src: "https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?width=4260&height=3975",
									srcSet:
										"https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?scale-down-to=512&width=4260&height=3975 512w,https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?scale-down-to=1024&width=4260&height=3975 1024w,https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?scale-down-to=2048&width=4260&height=3975 2048w,https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?scale-down-to=4096&width=4260&height=3975 4096w,https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?width=4260&height=3975 4260w",
								}}
								className={"framer-1gdt9xz"}
								data-framer-name={"Top White Patch"}
								layoutDependency={layoutDependency}
								layoutId={"QwPqeWzle"}
								{...addPropertyOverrides(
									{
										vyndh9pQD: {
											background: {
												alt: "Top Patch",
												fit: "fill",
												intrinsicHeight: 1987.5,
												intrinsicWidth: 2130,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 559) - 0 - 574.5) /
															2 +
															0 +
															0) +
														0,
												),
												pixelHeight: 3975,
												pixelWidth: 4260,
												sizes: `calc(${componentViewport?.width || "100vw"} - 20px)`,
												src: "https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?width=4260&height=3975",
												srcSet:
													"https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?scale-down-to=512&width=4260&height=3975 512w,https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?scale-down-to=1024&width=4260&height=3975 1024w,https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?scale-down-to=2048&width=4260&height=3975 2048w,https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?scale-down-to=4096&width=4260&height=3975 4096w,https://framerusercontent.com/images/y4oeET3EhGdxMf9biVp75kLcFxU.png?width=4260&height=3975 4260w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<Image
								as={"figure"}
								background={{
									alt: "Bottom Patch",
									fit: "fill",
									intrinsicHeight: 160.5,
									intrinsicWidth: 2130,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 486.5) - 0 - 690) / 2 +
												0 +
												0) +
											690 -
											87,
									),
									pixelHeight: 321,
									pixelWidth: 4260,
									sizes: `calc(${componentViewport?.width || "100vw"} - 40px)`,
									src: "https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?width=4260&height=321",
									srcSet:
										"https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?scale-down-to=512&width=4260&height=321 512w,https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?scale-down-to=1024&width=4260&height=321 1024w,https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?scale-down-to=2048&width=4260&height=321 2048w,https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?scale-down-to=4096&width=4260&height=321 4096w,https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?width=4260&height=321 4260w",
								}}
								className={"framer-ev7cjf"}
								data-framer-name={"Bottom White Patch"}
								layoutDependency={layoutDependency}
								layoutId={"BNv56Pxx0"}
								{...addPropertyOverrides(
									{
										vyndh9pQD: {
											background: {
												alt: "Bottom Patch",
												fit: "fill",
												intrinsicHeight: 160.5,
												intrinsicWidth: 2130,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 559) - 0 - 574.5) /
															2 +
															0 +
															0) +
														574.5 -
														87,
												),
												pixelHeight: 321,
												pixelWidth: 4260,
												sizes: `calc(${componentViewport?.width || "100vw"} - 20px)`,
												src: "https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?width=4260&height=321",
												srcSet:
													"https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?scale-down-to=512&width=4260&height=321 512w,https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?scale-down-to=1024&width=4260&height=321 1024w,https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?scale-down-to=2048&width=4260&height=321 2048w,https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?scale-down-to=4096&width=4260&height=321 4096w,https://framerusercontent.com/images/M2pRXyOLtwX0Bb7qzJItmeHM0.png?width=4260&height=321 4260w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<motion.div
								className={"framer-ae0jcr"}
								data-framer-name={"Text Container"}
								layoutDependency={layoutDependency}
								layoutId={"x0_Yn3Opw"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-17nmtuo"}
									data-framer-name={"H2-Title"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"eh5NVgzeV"}
									style={{
										"--extracted-1of0zx5":
											"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										"--extracted-hi0pf5":
											"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h2
											className={"framer-styles-preset-i6x10"}
											data-styles-preset={"Rr_znKXnP"}
											style={{
												"--framer-text-color":
													"var(--extracted-1of0zx5, var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255)))",
											}}
										>
											{"Prêt à transformer"}
										</motion.h2>
										<motion.h2
											className={"framer-styles-preset-i6x10"}
											data-styles-preset={"Rr_znKXnP"}
											style={{
												"--framer-text-color":
													"var(--extracted-hi0pf5, var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255)))",
											}}
										>
											{"votre activité ?"}
										</motion.h2>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-183kxy3"}
									data-framer-name={"Description"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"iPzUBhWOJ"}
									style={{
										"--extracted-2gxw0f":
											"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
										"--extracted-r6o4lv":
											"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
										"--framer-paragraph-spacing": "0px",
									}}
									variants={{
										vyndh9pQD: {
											"--extracted-r6o4lv":
												"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											vyndh9pQD: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1est8a"}
															data-styles-preset={"dJk2BbTAu"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
															}}
														>
															{
																"Rejoignez des milliers d'entreprises qui ont déjà transformé leur activité avec Wozif."
															}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
											dir={"auto"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224)))",
											}}
										>
											{"Rejoignez des milliers d'entreprises qui ont déjà"}
										</motion.p>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
											dir={"auto"}
											style={{
												"--framer-text-color":
													"var(--extracted-2gxw0f, var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224)))",
											}}
										>
											{"transformé leur activité avec Wozif."}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1m3bq0t"}
								data-framer-name={"Buttons Container"}
								layoutDependency={layoutDependency}
								layoutId={"ri40_IJsB"}
							>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "BbnwfmMeL",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "BbnwfmMeL",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "BbnwfmMeL",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks) => (
										<ComponentViewportProvider
											height={52}
											y={
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 486.5) - 0 - 690) / 2 +
													0 +
													0) +
												100 +
												438 +
												0
											}
											{...addPropertyOverrides(
												{
													vyndh9pQD: {
														width: `min(${componentViewport?.width || "100vw"} - 52px, 450px)`,
														y:
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 559) -
																0 -
																574.5) /
																2 +
																0 +
																0) +
															80 +
															300.5 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-zjt6nx-container"}
												layoutDependency={layoutDependency}
												layoutId={"uG8PTx6vf-container"}
												nodeId={"uG8PTx6vf"}
												rendersWithMotion={true}
												scopeId={"sgDJdh8KT"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "uG8PTx6vf",
													kxsr9hB1V: "Découvrir",
													layoutId: "uG8PTx6vf",
													m5s7pQQmA: resolvedLinks[0],
													NHtMIEDfO: false,
													TX7nunh0I: "14px 13px 14px 18px",
													variant: matchVariant("n1x39JHhO"),
													VteZZsIzV:
														"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
													width: "100%",
													ZueZHJx1j: true,
													...addPropertyOverrides(
														{
															tZjPsgXIP: {
																m5s7pQQmA: resolvedLinks[1],
															},
															vyndh9pQD: {
																m5s7pQQmA: resolvedLinks[2],
																style: {
																	width: "100%",
																},
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "Ai02WgZ_P",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "Ai02WgZ_P",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "Ai02WgZ_P",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks1) => (
										<ComponentViewportProvider
											height={50}
											y={
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 486.5) - 0 - 690) / 2 +
													0 +
													0) +
												100 +
												438 +
												1
											}
											{...addPropertyOverrides(
												{
													vyndh9pQD: {
														width: `min(${componentViewport?.width || "100vw"} - 52px, 450px)`,
														y:
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 559) -
																0 -
																574.5) /
																2 +
																0 +
																0) +
															80 +
															300.5 +
															0 +
															64,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-650a3-container"}
												layoutDependency={layoutDependency}
												layoutId={"tDYun2fzv-container"}
												nodeId={"tDYun2fzv"}
												rendersWithMotion={true}
												scopeId={"sgDJdh8KT"}
											>
												{_jsx(stdin_default3, {
													bLQDqyanN: stdin_default,
													EvFOC7YXo: false,
													height: "100%",
													id: "tDYun2fzv",
													J89Ucm84y: false,
													layoutId: "tDYun2fzv",
													LyePqFSL3: "center",
													QKqyYV11w:
														"var(--token-9ff70694-0783-4e61-9f6a-7b939313b3bd, rgb(38, 38, 38))",
													rNXUHBS8V: resolvedLinks1[0],
													variant: matchVariant("U2t_Okweq"),
													WB6m_In3A: "Qui sommes-nous",
													width: "100%",
													Y6bbgR64g: "14px 18px 14px 18px",
													ZSfEeTznX: 1,
													...addPropertyOverrides(
														{
															tZjPsgXIP: {
																rNXUHBS8V: resolvedLinks1[1],
															},
															vyndh9pQD: {
																rNXUHBS8V: resolvedLinks1[2],
																style: {
																	width: "100%",
																},
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-rbe9H.framer-1t5p703, .framer-rbe9H .framer-1t5p703 { display: block; }",
	".framer-rbe9H.framer-1dlajkh { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px 20px 0px 20px; position: relative; width: 1200px; }",
	".framer-rbe9H .framer-188fyus { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 100px 0px 100px 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-rbe9H .framer-ssldkb { aspect-ratio: 0.6391752577319587 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 485px); left: 0px; position: absolute; top: 0px; width: 310px; z-index: 2; }",
	".framer-rbe9H .framer-m8nv21 { aspect-ratio: 0.640495867768595 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 484px); position: absolute; right: 0px; top: 0px; width: 310px; z-index: 2; }",
	".framer-rbe9H .framer-zskf40 { aspect-ratio: 4.041811846689895 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 287px); left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-rbe9H .framer-1gdt9xz { aspect-ratio: 1.0716981132075472 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 1083px); left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-rbe9H .framer-ev7cjf { aspect-ratio: 13.271028037383177 / 1; bottom: 0px; flex: none; height: var(--framer-aspect-ratio-supported, 88px); left: 0px; overflow: visible; position: absolute; right: 0px; z-index: 3; }",
	".framer-rbe9H .framer-ae0jcr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 23px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 3; }",
	".framer-rbe9H .framer-17nmtuo, .framer-rbe9H .framer-183kxy3 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-rbe9H .framer-1m3bq0t { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; z-index: 3; }",
	".framer-rbe9H .framer-zjt6nx-container, .framer-rbe9H .framer-650a3-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-rbe9H.framer-v-nmn60l.framer-1dlajkh { width: 810px; }",
	".framer-rbe9H.framer-v-nmn60l .framer-ssldkb { left: -102px; }",
	".framer-rbe9H.framer-v-nmn60l .framer-m8nv21 { right: -102px; }",
	".framer-rbe9H.framer-v-nmn60l .framer-zskf40 { height: var(--framer-aspect-ratio-supported, 191px); }",
	".framer-rbe9H.framer-v-nmn60l .framer-1gdt9xz { height: var(--framer-aspect-ratio-supported, 719px); }",
	".framer-rbe9H.framer-v-nmn60l .framer-ev7cjf { height: var(--framer-aspect-ratio-supported, 58px); }",
	".framer-rbe9H.framer-v-1k5cmzq.framer-1dlajkh { padding: 0px 10px 0px 10px; width: 400px; }",
	".framer-rbe9H.framer-v-1k5cmzq .framer-188fyus { gap: 30px; padding: 80px 16px 80px 16px; }",
	".framer-rbe9H.framer-v-1k5cmzq .framer-zskf40 { height: var(--framer-aspect-ratio-supported, 94px); }",
	".framer-rbe9H.framer-v-1k5cmzq .framer-1gdt9xz { height: var(--framer-aspect-ratio-supported, 355px); }",
	".framer-rbe9H.framer-v-1k5cmzq .framer-ev7cjf { height: var(--framer-aspect-ratio-supported, 29px); }",
	".framer-rbe9H.framer-v-1k5cmzq .framer-ae0jcr { max-width: 450px; }",
	".framer-rbe9H.framer-v-1k5cmzq .framer-1m3bq0t { flex-direction: column; max-width: 450px; width: 100%; }",
	".framer-rbe9H.framer-v-1k5cmzq .framer-zjt6nx-container, .framer-rbe9H.framer-v-1k5cmzq .framer-650a3-container { width: 100%; }",
	...css2,
	...css,
];
var FramersgDJdh8KT = withCSS(Component, css3, "framer-rbe9H");
var stdin_default4 = FramersgDJdh8KT;
FramersgDJdh8KT.displayName = "Helper/CTA";
FramersgDJdh8KT.defaultProps = {
	height: 486.5,
	width: 1200,
};
addPropertyControls(FramersgDJdh8KT, {
	variant: {
		options: ["NJJqXtw1K", "tZjPsgXIP", "vyndh9pQD"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramersgDJdh8KT,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonPrimaryButtonFonts,
		...ButtonSecondaryButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:helper/cta
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "vyndh9pQD",
	md: "tZjPsgXIP",
	xl: "NJJqXtw1K",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var cta_default = ComponentWithRoot;
export { cta_default as default };
