// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Type-1 Vertically Aligned' | 'Type-2 Horizontally Aligned' // Variant
 * icon?: undefined // Icon
 * text?: string // Text
 * alpha?: number // Alpha
 * width?: number // Width
}} Props

 */
import { stdin_default } from "../chunks/chunk-7TI3OG4T.js";
import "../chunks/chunk-6KOE3X73.js";
import { className, css, fonts } from "../chunks/chunk-XSMFK32U.js";
import { routes } from "../chunks/chunk-643FN7SQ.js";

// virtual:helper/section-sub-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ttq8R26wEIhpxFYxOwNH/6XWVqHCdyAmN76HKXgqH/iFTj4MuTx.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/5v0jJmF3sqacmaChkilJ/EvP62127oCCRX7qec3u2/VByNAqDgV.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0.553 12.993 C 0.178 11.927 -0.009 10.804 0 9.674 C 0.042 4.313 4.475 -0.047 9.844 0 C 12.991 0.033 15.929 1.582 17.735 4.16 C 19.54 6.738 19.992 10.028 18.947 12.997 C 18.842 13.299 18.557 13.501 18.238 13.5 L 1.262 13.5 C 0.942 13.499 0.658 13.296 0.553 12.993 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="13.500390761991643px" id="QappaZYIk" transform="translate(2.25 4.5)" width="19.50038574567636px"/><path d="M 0 9 L 9 0" fill="transparent" height="9px" id="G8GzP3VyB" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(11.25 6)" width="9px"/><path d="M 0.041 7.5 C 0.014 7.251 0 7.001 0 6.75 C 0.002 4.577 1.049 2.537 2.814 1.269 C 4.579 0.001 6.846 -0.34 8.906 0.352" fill="transparent" height="7.49995077170297px" id="C6phhqlEb" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(5.25 7.5)" width="8.90625px"/><path d="M 18.433 5.31 C 19.649 7.695 19.834 10.473 18.947 12.998 C 18.842 13.3 18.557 13.502 18.238 13.501 L 1.262 13.501 C 0.942 13.5 0.658 13.297 0.553 12.994 C 0.178 11.928 -0.009 10.805 0 9.674 C 0.042 4.313 4.475 -0.047 9.844 0 C 11.357 0.013 12.847 0.378 14.194 1.067" fill="transparent" height="13.501328261991645px" id="UMCoxM0Em" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(2.25 4.5)" width="19.500561704642013px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("2344544179", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-N3ZwU", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css2 = [
	`.framer-N3ZwU { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css2, "framer-N3ZwU");
Icon.displayName = "Speedometer";
var stdin_default2 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/ttq8R26wEIhpxFYxOwNH/6XWVqHCdyAmN76HKXgqH/iFTj4MuTx.js
var HelperIconContainerFonts = getFonts(stdin_default);
var cycleOrder = ["P2kOjvAwt", "OfUJRskHF"];
var serializationHash = "framer-ZLD1t";
var variantClassNames = {
	OfUJRskHF: "framer-v-1gwrbpu",
	P2kOjvAwt: "framer-v-1l9qpp5",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	"Type-1 Vertically Aligned": "P2kOjvAwt",
	"Type-2 Horizontally Aligned": "OfUJRskHF",
};
var getProps2 = ({
	alpha,
	height,
	icon,
	id,
	text,
	width,
	width1,
	...props
}) => {
	return {
		...props,
		mcGDEhJba: alpha ?? props.mcGDEhJba ?? 0.5,
		Rn3Ixtvb9: text ?? props.Rn3Ixtvb9 ?? "Predict and send reply likelihood",
		rQZVws5Cn: width1 ?? props.rQZVws5Cn ?? 1.5,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "P2kOjvAwt",
		VhzSOZs4m: icon ?? props.VhzSOZs4m ?? stdin_default2,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		VhzSOZs4m: VhzSOZs4m2,
		Rn3Ixtvb9: Rn3Ixtvb92,
		mcGDEhJba: mcGDEhJba2,
		rQZVws5Cn: rQZVws5Cn2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "P2kOjvAwt",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1l9qpp5",
							className2,
							classNames,
						)}
						data-framer-name={"Type-1 Vertically Aligned"}
						layoutDependency={layoutDependency}
						layoutId={"P2kOjvAwt"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
							borderBottomLeftRadius: 12,
							borderBottomRightRadius: 12,
							borderTopLeftRadius: 12,
							borderTopRightRadius: 12,
							boxShadow:
								"0px 1px 1px 0px rgba(0, 0, 0, 0.15), 0px 3px 3px 0px rgba(0, 0, 0, 0.05)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								OfUJRskHF: {
									"data-framer-name": "Type-2 Horizontally Aligned",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={24}
							y={
								(componentViewport?.y || 0) +
								16 +
								(((componentViewport?.height || 112) - 32 - 152) / 2 + 0 + 0)
							}
							{...addPropertyOverrides(
								{
									OfUJRskHF: {
										y: (componentViewport?.y || 0) + 16,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-nfpz7f-container"}
								layoutDependency={layoutDependency}
								layoutId={"JUOt7zA6i-container"}
								nodeId={"JUOt7zA6i"}
								rendersWithMotion={true}
								scopeId={"iFTj4MuTx"}
							>
								{_jsx2(stdin_default, {
									B8b2V9fZA: VhzSOZs4m2,
									E3bx3k8kp: rQZVws5Cn2,
									height: "100%",
									id: "JUOt7zA6i",
									layoutId: "JUOt7zA6i",
									pF3i9Z3QX: mcGDEhJba2,
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1t651p8"}
							data-framer-name={"Text"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"HBZpypzVu"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-421e20c4-0040-4023-a28d-103276930f09, rgb(77, 77, 77))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={Rn3Ixtvb92}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion2.p
									className={"framer-styles-preset-1wiboy8"}
									data-styles-preset={"V8awtwKCk"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-421e20c4-0040-4023-a28d-103276930f09, rgb(77, 77, 77)))",
									}}
								>
									{"Predict and send reply likelihood"}
								</motion2.p>
							</React2.Fragment>
						</RichText>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ZLD1t.framer-knroc9, .framer-ZLD1t .framer-knroc9 { display: block; }",
	".framer-ZLD1t.framer-1l9qpp5 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 16px; position: relative; width: 170px; }",
	".framer-ZLD1t .framer-nfpz7f-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-ZLD1t .framer-1t651p8 { flex: none; height: auto; max-width: 140px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-ZLD1t.framer-v-1gwrbpu.framer-1l9qpp5 { flex-direction: row; justify-content: flex-start; width: 252px; }",
	".framer-ZLD1t.framer-v-1gwrbpu .framer-1t651p8 { flex: 1 0 0px; max-width: unset; width: 1px; }",
	...css,
];
var FrameriFTj4MuTx = withCSS2(Component2, css3, "framer-ZLD1t");
var stdin_default3 = FrameriFTj4MuTx;
FrameriFTj4MuTx.displayName = "Helper/Section Sub Card";
FrameriFTj4MuTx.defaultProps = {
	height: 112,
	width: 170,
};
addPropertyControls2(FrameriFTj4MuTx, {
	variant: {
		options: ["P2kOjvAwt", "OfUJRskHF"],
		optionTitles: ["Type-1 Vertically Aligned", "Type-2 Horizontally Aligned"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	VhzSOZs4m: {
		defaultValue: {
			identifier:
				"module:5v0jJmF3sqacmaChkilJ/EvP62127oCCRX7qec3u2/VByNAqDgV.js:default",
			moduleId: "5v0jJmF3sqacmaChkilJ",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon",
		type: ControlType2.VectorSetItem,
	},
	Rn3Ixtvb9: {
		defaultValue: "Predict and send reply likelihood",
		displayTextArea: false,
		title: "Text",
		type: ControlType2.String,
	},
	mcGDEhJba: {
		defaultValue: 0.5,
		displayStepper: true,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType2.Number,
	},
	rQZVws5Cn: {
		defaultValue: 1.5,
		displayStepper: true,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType2.Number,
	},
});
addFonts(
	FrameriFTj4MuTx,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...HelperIconContainerFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:helper/section-sub-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "OfUJRskHF",
	xl: "P2kOjvAwt",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SectionSubCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var section_sub_card_default = ComponentWithRoot;
export { section_sub_card_default as default };
