// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Yes' | 'No' // Variant
}} Props

 */
import { stdin_default } from "../chunks/chunk-UWDAN3I7.js";
import { className, css, fonts } from "../chunks/chunk-DRXSNPA2.js";
import { routes } from "../chunks/chunk-643FN7SQ.js";

// virtual:helper/yes-no
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/faqHj8kZY7u3uuA1VEQi/tQZmEWdwcyREPIRHFRa2/oMt7T2PiB.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var CheckFonts = getFonts(stdin_default);
var cycleOrder = ["hdLcwNLoJ", "nsD3ZP7ld"];
var serializationHash = "framer-0D9xw";
var variantClassNames = {
	hdLcwNLoJ: "framer-v-18hiqw6",
	nsD3ZP7ld: "framer-v-1duv6vh",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	No: "nsD3ZP7ld",
	Yes: "hdLcwNLoJ",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "hdLcwNLoJ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "hdLcwNLoJ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "nsD3ZP7ld") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "nsD3ZP7ld") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-18hiqw6",
							className2,
							classNames,
						)}
						data-framer-name={"Yes"}
						layoutDependency={layoutDependency}
						layoutId={"hdLcwNLoJ"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								nsD3ZP7ld: {
									"data-framer-name": "No",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<motion.div
								className={"framer-s4e6pa"}
								data-framer-name={"Sub Container"}
								layoutDependency={layoutDependency}
								layoutId={"eXmdK4OqR"}
								style={{
									backgroundColor: "rgb(182, 242, 207)",
									borderBottomLeftRadius: 6,
									borderBottomRightRadius: 6,
									borderTopLeftRadius: 6,
									borderTopRightRadius: 6,
								}}
							>
								{_jsx(stdin_default, {
									animated: true,
									className: "framer-axuvyy",
									layoutDependency,
									layoutId: "FLJu1wW2a",
									style: {
										"--1m6trwb": 0,
										"--21h8s6": "rgb(6, 96, 45)",
										"--pgex8v": 3,
									},
								})}
							</motion.div>
						)}
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-165fqu2"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"A5GJciVUf"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-421e20c4-0040-4023-a28d-103276930f09, rgb(77, 77, 77))",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1dqim52"}
										data-styles-preset={"QowBsUafH"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-421e20c4-0040-4023-a28d-103276930f09, rgb(77, 77, 77)))",
										}}
									>
										{"Yes"}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						{isDisplayed1() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1xlhkif"}
								data-framer-name={"----"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"rq26tRMyw"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1dqim52"}
										data-styles-preset={"QowBsUafH"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
										}}
									>
										{"----"}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-0D9xw.framer-1vhbt2j, .framer-0D9xw .framer-1vhbt2j { display: block; }",
	".framer-0D9xw.framer-18hiqw6 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
	".framer-0D9xw .framer-s4e6pa { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 22px); justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 22px; will-change: var(--framer-will-change-override, transform); }",
	".framer-0D9xw .framer-axuvyy { flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }",
	".framer-0D9xw .framer-165fqu2, .framer-0D9xw .framer-1xlhkif { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
];
var FrameroMt7T2PiB = withCSS(Component, css2, "framer-0D9xw");
var stdin_default2 = FrameroMt7T2PiB;
FrameroMt7T2PiB.displayName = "Helper/Yes-No";
FrameroMt7T2PiB.defaultProps = {
	height: 22.5,
	width: 55,
};
addPropertyControls(FrameroMt7T2PiB, {
	variant: {
		options: ["hdLcwNLoJ", "nsD3ZP7ld"],
		optionTitles: ["Yes", "No"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FrameroMt7T2PiB,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...CheckFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:helper/yes-no
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "hdLcwNLoJ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders YesNoFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var yes_no_default = ComponentWithRoot;
export { yes_no_default as default };
