packages:
  - packages/**
  - .
  - e2e
  - apps/desktop/src/main

onlyBuiltDependencies:
  - '@playwright/browser-chromium'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - '@vercel/speed-insights'
  - '@lobehub/editor'
  - better-sqlite3
  - core-js
  - core-js-pure
  - electron
  - es5-ext
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver

overrides:
  '@lobehub/chat-plugin-sdk>swagger-client': 3.36.0
  '@swagger-api/apidom-reference': 1.1.0
  jose: ^6.1.3
  stylelint-config-clean-order: 7.0.0
  pdfjs-dist: 5.4.530

patchedDependencies:
  '@swagger-api/apidom-reference': patches/@swagger-api__apidom-reference.patch
  '@upstash/qstash': patches/@upstash__qstash.patch
