// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * click?: Function // Click
}} Props

 */
import { stdin_default } from "./chunks/chunk-BTEBRY5G.js";
import { className, css, fonts } from "./chunks/chunk-SXEUHOLR.js";
import { routes } from "./chunks/chunk-643FN7SQ.js";

// virtual:big-watch-demo-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/cGDQElZcJDRYF6gttIoM/xIrnzGzaG1qkkx4AR5ga/fsoso5Q1W.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PlayFonts = getFonts(stdin_default);
var enabledGestures = {
	BmZV4tjvu: {
		hover: true,
	},
};
var serializationHash = "framer-JEKd7";
var variantClassNames = {
	BmZV4tjvu: "framer-v-16kwbtc",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		Vc6icSMl1: click ?? props.Vc6icSMl1,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		Vc6icSMl1: Vc6icSMl12,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "BmZV4tjvu",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapxm0yf3 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Vc6icSMl12) {
			const res = await Vc6icSMl12(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-16kwbtc",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"BmZV4tjvu"}
						onTap={onTapxm0yf3}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"BmZV4tjvu-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-16mtops"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"hpZ1iwnNf"}
							style={{
								opacity: 0.8,
							}}
						>
							<motion.div
								className={"framer-gjn97g"}
								data-framer-name={"Sub Container"}
								layoutDependency={layoutDependency}
								layoutId={"sXKtWwtZk"}
							>
								<motion.div
									className={"framer-1ybbhe5"}
									data-framer-name={"Wave Container"}
									layoutDependency={layoutDependency}
									layoutId={"hMQ_R82Sc"}
								>
									<motion.div
										className={"framer-omnztb"}
										data-border={true}
										data-framer-name={"Wave-3"}
										layoutDependency={layoutDependency}
										layoutId={"qc8m8d6Mn"}
										style={{
											"--border-bottom-width": "6.27712345123291px",
											"--border-color":
												"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
											"--border-left-width": "6.27712345123291px",
											"--border-right-width": "6.27712345123291px",
											"--border-style": "solid",
											"--border-top-width": "6.27712345123291px",
											borderBottomLeftRadius: 78464045e-1,
											borderBottomRightRadius: 78464045e-1,
											borderTopLeftRadius: 78464045e-1,
											borderTopRightRadius: 78464045e-1,
											filter: "blur(7.846405029296875px)",
											WebkitFilter: "blur(7.846405029296875px)",
										}}
									/>
									<motion.div
										className={"framer-gxwid"}
										data-border={true}
										data-framer-name={"Wave-2"}
										layoutDependency={layoutDependency}
										layoutId={"HxcnPCk_K"}
										style={{
											"--border-bottom-width": "3.9232025146484375px",
											"--border-color":
												"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
											"--border-left-width": "3.9232025146484375px",
											"--border-right-width": "3.9232025146484375px",
											"--border-style": "solid",
											"--border-top-width": "3.9232025146484375px",
											borderBottomLeftRadius: 78464045e-1,
											borderBottomRightRadius: 78464045e-1,
											borderTopLeftRadius: 78464045e-1,
											borderTopRightRadius: 78464045e-1,
											filter: "blur(7.846405029296875px)",
											WebkitFilter: "blur(7.846405029296875px)",
										}}
									/>
									<motion.div
										className={"framer-14rrj9m"}
										data-border={true}
										data-framer-name={"Wave-1"}
										layoutDependency={layoutDependency}
										layoutId={"t93zYyDB_"}
										style={{
											"--border-bottom-width": "3.9232025146484375px",
											"--border-color":
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											"--border-left-width": "3.9232025146484375px",
											"--border-right-width": "3.9232025146484375px",
											"--border-style": "solid",
											"--border-top-width": "3.9232025146484375px",
											borderBottomLeftRadius: 78464045e-1,
											borderBottomRightRadius: 78464045e-1,
											borderTopLeftRadius: 78464045e-1,
											borderTopRightRadius: 78464045e-1,
											filter: "blur(3.9232025146484375px)",
											WebkitFilter: "blur(3.9232025146484375px)",
										}}
									/>
								</motion.div>
								<motion.div
									className={"framer-bbmln2"}
									data-framer-name={"Wave Container"}
									layoutDependency={layoutDependency}
									layoutId={"PFoVx9y2N"}
								>
									<motion.div
										className={"framer-2kdmd3"}
										data-border={true}
										data-framer-name={"Wave-3"}
										layoutDependency={layoutDependency}
										layoutId={"YmPy92R7l"}
										style={{
											"--border-bottom-width": "6.27712345123291px",
											"--border-color":
												"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
											"--border-left-width": "6.27712345123291px",
											"--border-right-width": "6.27712345123291px",
											"--border-style": "solid",
											"--border-top-width": "6.27712345123291px",
											borderBottomLeftRadius: 78464045e-1,
											borderBottomRightRadius: 78464045e-1,
											borderTopLeftRadius: 78464045e-1,
											borderTopRightRadius: 78464045e-1,
											filter: "blur(7.846405029296875px)",
											WebkitFilter: "blur(7.846405029296875px)",
										}}
									/>
									<motion.div
										className={"framer-wrr5ty"}
										data-border={true}
										data-framer-name={"Wave-2"}
										layoutDependency={layoutDependency}
										layoutId={"VXizJmUzZ"}
										style={{
											"--border-bottom-width": "3.9232025146484375px",
											"--border-color":
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											"--border-left-width": "3.9232025146484375px",
											"--border-right-width": "3.9232025146484375px",
											"--border-style": "solid",
											"--border-top-width": "3.9232025146484375px",
											borderBottomLeftRadius: 78464045e-1,
											borderBottomRightRadius: 78464045e-1,
											borderTopLeftRadius: 78464045e-1,
											borderTopRightRadius: 78464045e-1,
											filter: "blur(7.846405029296875px)",
											WebkitFilter: "blur(7.846405029296875px)",
										}}
									/>
									<motion.div
										className={"framer-xcrbt1"}
										data-border={true}
										data-framer-name={"Wave-1"}
										layoutDependency={layoutDependency}
										layoutId={"sbC9BnEZi"}
										style={{
											"--border-bottom-width": "3.9232025146484375px",
											"--border-color":
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											"--border-left-width": "3.9232025146484375px",
											"--border-right-width": "3.9232025146484375px",
											"--border-style": "solid",
											"--border-top-width": "3.9232025146484375px",
											borderBottomLeftRadius: 78464045e-1,
											borderBottomRightRadius: 78464045e-1,
											borderTopLeftRadius: 78464045e-1,
											borderTopRightRadius: 78464045e-1,
											filter: "blur(3.9232025146484375px)",
											WebkitFilter: "blur(3.9232025146484375px)",
										}}
									/>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-13aqoqb"}
								data-framer-name={"Wave Container"}
								layoutDependency={layoutDependency}
								layoutId={"V3pgMXmd9"}
								style={{
									opacity: 0.5,
								}}
							>
								<motion.div
									className={"framer-190kzvu"}
									data-framer-name={"Inner Waves"}
									layoutDependency={layoutDependency}
									layoutId={"a5gZhqHsD"}
								>
									<motion.div
										className={"framer-1jpn0jd"}
										data-border={true}
										data-framer-name={"Wave-3"}
										layoutDependency={layoutDependency}
										layoutId={"gD8tEU_z1"}
										style={{
											"--border-bottom-width": "6.27712345123291px",
											"--border-color":
												"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
											"--border-left-width": "6.27712345123291px",
											"--border-right-width": "6.27712345123291px",
											"--border-style": "solid",
											"--border-top-width": "6.27712345123291px",
											borderBottomLeftRadius: 78464056,
											borderBottomRightRadius: 78464056,
											borderTopLeftRadius: 78464056,
											borderTopRightRadius: 78464056,
											filter: "blur(7.846405029296875px)",
											WebkitFilter: "blur(7.846405029296875px)",
										}}
									/>
									<motion.div
										className={"framer-9k8tb8"}
										data-border={true}
										data-framer-name={"Wave-2"}
										layoutDependency={layoutDependency}
										layoutId={"FFuV_LY9e"}
										style={{
											"--border-bottom-width": "3.9232025146484375px",
											"--border-color":
												"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
											"--border-left-width": "3.9232025146484375px",
											"--border-right-width": "3.9232025146484375px",
											"--border-style": "solid",
											"--border-top-width": "3.9232025146484375px",
											borderBottomLeftRadius: 78464056,
											borderBottomRightRadius: 78464056,
											borderTopLeftRadius: 78464056,
											borderTopRightRadius: 78464056,
											filter: "blur(7.846405029296875px)",
											WebkitFilter: "blur(7.846405029296875px)",
										}}
									/>
									<motion.div
										className={"framer-9ji4vu"}
										data-border={true}
										data-framer-name={"Wave-1"}
										layoutDependency={layoutDependency}
										layoutId={"yyAOd2rF0"}
										style={{
											"--border-bottom-width": "3.9232025146484375px",
											"--border-color":
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											"--border-left-width": "3.9232025146484375px",
											"--border-right-width": "3.9232025146484375px",
											"--border-style": "solid",
											"--border-top-width": "3.9232025146484375px",
											borderBottomLeftRadius: 78464056,
											borderBottomRightRadius: 78464056,
											borderTopLeftRadius: 78464056,
											borderTopRightRadius: 78464056,
											filter: "blur(3.9232025146484375px)",
											WebkitFilter: "blur(3.9232025146484375px)",
										}}
									/>
								</motion.div>
								<motion.div
									className={"framer-foa20r"}
									data-framer-name={"Sub Container"}
									layoutDependency={layoutDependency}
									layoutId={"zIk3nQn6l"}
								>
									<motion.div
										className={"framer-k0wwz1"}
										data-border={true}
										data-framer-name={"Wave-3"}
										layoutDependency={layoutDependency}
										layoutId={"R8vthTj4H"}
										style={{
											"--border-bottom-width": "6.27712345123291px",
											"--border-color":
												"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
											"--border-left-width": "6.27712345123291px",
											"--border-right-width": "6.27712345123291px",
											"--border-style": "solid",
											"--border-top-width": "6.27712345123291px",
											borderBottomLeftRadius: 78464056,
											borderBottomRightRadius: 78464056,
											borderTopLeftRadius: 78464056,
											borderTopRightRadius: 78464056,
											filter: "blur(7.846405029296875px)",
											WebkitFilter: "blur(7.846405029296875px)",
										}}
									/>
									<motion.div
										className={"framer-kncgnp"}
										data-border={true}
										data-framer-name={"Wave-2"}
										layoutDependency={layoutDependency}
										layoutId={"vkIUvQQKK"}
										style={{
											"--border-bottom-width": "3.9232025146484375px",
											"--border-color":
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											"--border-left-width": "3.9232025146484375px",
											"--border-right-width": "3.9232025146484375px",
											"--border-style": "solid",
											"--border-top-width": "3.9232025146484375px",
											borderBottomLeftRadius: 78464056,
											borderBottomRightRadius: 78464056,
											borderTopLeftRadius: 78464056,
											borderTopRightRadius: 78464056,
											filter: "blur(7.846405029296875px)",
											WebkitFilter: "blur(7.846405029296875px)",
										}}
									/>
									<motion.div
										className={"framer-zg2vq0"}
										data-border={true}
										data-framer-name={"Wave-1"}
										layoutDependency={layoutDependency}
										layoutId={"lTrqvd7lR"}
										style={{
											"--border-bottom-width": "3.9232025146484375px",
											"--border-color":
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											"--border-left-width": "3.9232025146484375px",
											"--border-right-width": "3.9232025146484375px",
											"--border-style": "solid",
											"--border-top-width": "3.9232025146484375px",
											borderBottomLeftRadius: 78464056,
											borderBottomRightRadius: 78464056,
											borderTopLeftRadius: 78464056,
											borderTopRightRadius: 78464056,
											filter: "blur(3.9232025146484375px)",
											WebkitFilter: "blur(3.9232025146484375px)",
										}}
									/>
								</motion.div>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-h0mtzq"}
							data-framer-name={"Button"}
							layoutDependency={layoutDependency}
							layoutId={"J8f7zmNfc"}
							style={{
								backgroundColor:
									"var(--token-aa15e029-4bb1-434e-9852-151a8d809557, rgb(26, 26, 26))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								boxShadow:
									"0px 5.8510637283325195px 12.872340202331543px 0px rgba(148, 148, 148, 0.33), 0px 23.404254913330078px 23.404254913330078px 0px rgba(148, 148, 148, 0.29), 0px 52.65957260131836px 31.595745086669922px 0px rgba(148, 148, 148, 0.17), 0px 94.7872314453125px 37.446807861328125px 0px rgba(148, 148, 148, 0.05), 0px 147.44680786132812px 40.95744705200195px 0px rgba(148, 148, 148, 0.01)",
							}}
							transformTemplate={transformTemplate1}
						>
							<motion.div
								className={"framer-gryh2w"}
								data-border={true}
								data-framer-name={"Button"}
								layoutDependency={layoutDependency}
								layoutId={"HtQi0LYip"}
								style={{
									"--border-bottom-width": "0px",
									"--border-color": "rgba(255, 255, 255, 0.15)",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "1.170212745666504px",
									backgroundColor:
										"var(--token-9ff70694-0783-4e61-9f6a-7b939313b3bd, rgb(38, 38, 38))",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
									boxShadow:
										"0px 3px 7px 0px rgba(82, 82, 82, 0.1), 0px 11px 11px 0px rgba(82, 82, 82, 0.09), 0px 26px 16px 0px rgba(82, 82, 82, 0.05), 0px 46px 18px 0px rgba(82, 82, 82, 0.01), 0px 73px 21px 0px rgba(82, 82, 82, 0), inset 0px 2px 2px 0px rgba(255, 255, 255, 0.34)",
								}}
								variants={{
									"BmZV4tjvu-hover": {
										backgroundColor:
											"var(--token-421e20c4-0040-4023-a28d-103276930f09, rgb(77, 77, 77))",
									},
								}}
							>
								{_jsx(stdin_default, {
									animated: true,
									className: "framer-1gj3pyk",
									layoutDependency,
									layoutId: "b4VEVPNQ_",
									style: {
										"--1m6trwb": 1,
										"--21h8s6":
											"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										"--pgex8v": 1.5,
									},
								})}
								<RichText
									__fromCanvasComponent={true}
									className={"framer-2v538"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"gxtFQqZIb"}
									style={{
										"--extracted-1w1cjl5":
											"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h6
											className={"framer-styles-preset-kk6hck"}
											data-styles-preset={"SIbAeTqgh"}
											style={{
												"--framer-text-color":
													"var(--extracted-1w1cjl5, var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255)))",
											}}
										>
											{"Watch Demo"}
										</motion.h6>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JEKd7.framer-1absxfw, .framer-JEKd7 .framer-1absxfw { display: block; }",
	".framer-JEKd7.framer-16kwbtc { cursor: pointer; gap: 0px; height: 220px; overflow: visible; position: relative; width: 349px; }",
	".framer-JEKd7 .framer-16mtops { flex: none; height: 220px; left: 0px; mix-blend-mode: luminosity; overflow: visible; position: absolute; top: 0px; width: 348px; }",
	".framer-JEKd7 .framer-gjn97g { flex: none; height: 119px; left: 53px; overflow: visible; position: absolute; top: 50px; width: 241px; }",
	".framer-JEKd7 .framer-1ybbhe5 { flex: none; height: 85px; left: 23px; overflow: visible; position: absolute; top: 17px; width: 195px; }",
	".framer-JEKd7 .framer-omnztb { flex: none; height: 85px; left: calc(50% - 194.59083557128906px / 2); position: absolute; top: calc(50% - 84.74116516113281px / 2); width: 195px; }",
	".framer-JEKd7 .framer-gxwid { flex: none; height: 78px; left: calc(49.99583617750116% - 183.6058807373047px / 2); position: absolute; top: calc(50.00013054602269% - 78.46404266357422px / 2); width: 184px; }",
	".framer-JEKd7 .framer-14rrj9m { flex: none; height: 72px; left: calc(49.996898697178366% - 177.32876586914062px / 2); position: absolute; top: calc(49.99997749206505% - 72.18692779541016px / 2); width: 177px; }",
	".framer-JEKd7 .framer-bbmln2 { flex: none; height: 119px; left: 0px; overflow: visible; position: absolute; top: 0px; width: 241px; }",
	".framer-JEKd7 .framer-2kdmd3 { flex: none; height: 119px; left: calc(50% - 241.43678283691406px / 2); position: absolute; top: calc(50% - 119.2653579711914px / 2); width: 241px; }",
	".framer-JEKd7 .framer-wrr5ty { flex: none; height: 110px; left: calc(50.00230679763968% - 227.8072967529297px / 2); position: absolute; top: calc(50.00020150522484% - 110.43087768554688px / 2); width: 228px; }",
	".framer-JEKd7 .framer-xcrbt1 { flex: none; height: 102px; left: calc(49.99761420244115% - 220.01901245117188px / 2); position: absolute; top: calc(49.999996801504366% - 101.59640502929688px / 2); width: 220px; }",
	".framer-JEKd7 .framer-13aqoqb, .framer-JEKd7 .framer-foa20r { flex: none; height: 220px; left: 0px; overflow: visible; position: absolute; top: 0px; width: 348px; }",
	".framer-JEKd7 .framer-190kzvu { flex: none; height: 156px; left: 34px; overflow: visible; position: absolute; top: 32px; width: 281px; }",
	".framer-JEKd7 .framer-1jpn0jd { flex: none; height: 156px; left: calc(50% - 280.7832946777344px / 2); position: absolute; top: calc(50% - 156.10214233398438px / 2); width: 281px; }",
	".framer-JEKd7 .framer-9k8tb8 { flex: none; height: 145px; left: calc(49.99876096478238% - 264.9325866699219px / 2); position: absolute; top: calc(50.00011729849828% - 144.53903198242188px / 2); width: 265px; }",
	".framer-JEKd7 .framer-9ji4vu { flex: none; height: 133px; left: calc(49.99965491782316% - 255.87510681152344px / 2); position: absolute; top: calc(49.999916913563716% - 132.9759063720703px / 2); width: 256px; }",
	".framer-JEKd7 .framer-k0wwz1 { flex: none; height: 220px; left: calc(50.00000000000002% - 348px / 2); position: absolute; top: calc(50.00000000000002% - 220px / 2); width: 348px; }",
	".framer-JEKd7 .framer-kncgnp { flex: none; height: 203px; left: calc(50.000762108858574% - 328.71270751953125px / 2); position: absolute; top: calc(50.00008334365869% - 203.42529296875px / 2); width: 329px; }",
	".framer-JEKd7 .framer-zg2vq0 { flex: none; height: 187px; left: calc(50.0024746638224% - 317.4746398925781px / 2); position: absolute; top: calc(49.99995138286577% - 187.15127563476562px / 2); width: 317px; }",
	".framer-JEKd7 .framer-h0mtzq { align-content: flex-start; align-items: flex-start; bottom: 79px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 11.702127456665039px; height: min-content; justify-content: flex-start; left: 50%; overflow: visible; padding: 1px; position: absolute; width: min-content; }",
	".framer-JEKd7 .framer-gryh2w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 9px; height: min-content; justify-content: center; overflow: visible; padding: 16px 16px 16px 14px; position: relative; width: min-content; }",
	".framer-JEKd7 .framer-1gj3pyk { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-JEKd7 .framer-2v538 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-JEKd7.framer-v-16kwbtc.hover .framer-zg2vq0 { bottom: 0px; height: unset; left: 0px; right: 0px; top: 0px; width: unset; }",
	...css,
	'.framer-JEKd7[data-border="true"]::after, .framer-JEKd7 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Framerfsoso5Q1W = withCSS(Component, css2, "framer-JEKd7");
var stdin_default2 = Framerfsoso5Q1W;
Framerfsoso5Q1W.displayName = "Big Watch Demo Button";
Framerfsoso5Q1W.defaultProps = {
	height: 220,
	width: 349,
};
addPropertyControls(Framerfsoso5Q1W, {
	Vc6icSMl1: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	Framerfsoso5Q1W,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PlayFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:big-watch-demo-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BigWatchDemoButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var big_watch_demo_button_default = ComponentWithRoot;
export { big_watch_demo_button_default as default };
