// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Open' | 'Closed' // Variant
 * question?: string // Question
 * answer?: string // Answer
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-SXEUHOLR.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-XSMFK32U.js";
import { routes } from "./chunks/chunk-643FN7SQ.js";

// virtual:faq-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6Kgnm5ZtHNZyoJSk974w/lIyqFNSPBvvLsu2Ydekx/f4N6Pei1z.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["IS4Ic9o6Y", "lzZiJXpZ6"];
var serializationHash = "framer-MPW3t";
var variantClassNames = {
	IS4Ic9o6Y: "framer-v-14efhkn",
	lzZiJXpZ6: "framer-v-1fjwzoj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Closed: "lzZiJXpZ6",
	Open: "IS4Ic9o6Y",
};
var getProps = ({ answer, height, id, question, width, ...props }) => {
	return {
		...props,
		T8rQFvSBR:
			answer ??
			props.T8rQFvSBR ??
			"Ametrix is an AI-powered inbox automation platform that drafts replies, schedules follow-ups, scores leads, and organizes email workflows so teams can move faster with less manual effort.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "IS4Ic9o6Y",
		W88zB8mIG: question ?? props.W88zB8mIG ?? "What is Ametrix?",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		W88zB8mIG: W88zB8mIG2,
		T8rQFvSBR: T8rQFvSBR2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "IS4Ic9o6Y",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap9ucvao = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("lzZiJXpZ6");
	});
	const onTaprvp4xg = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("IS4Ic9o6Y");
	});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "lzZiJXpZ6") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-14efhkn",
							className3,
							classNames,
						)}
						data-framer-name={"Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"IS4Ic9o6Y"}
						onTap={onTap9ucvao}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								lzZiJXpZ6: {
									"data-framer-name": "Closed",
									onTap: onTaprvp4xg,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-hxm6di"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"zyVPce_SV"}
							style={{
								backgroundColor:
									"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								boxShadow: "0px 1px 1px 0px rgba(0, 0, 0, 0.15)",
							}}
							variants={{
								lzZiJXpZ6: {
									backgroundColor:
										"var(--token-422cf5f3-5896-4764-a5ee-34eb86328eac, rgb(234, 234, 234))",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
									boxShadow: "0px 1px 1px 0px rgba(0, 0, 0, 0)",
								},
							}}
						>
							<motion.div
								className={"framer-1egiif8"}
								data-framer-name={"Question"}
								layoutDependency={layoutDependency}
								layoutId={"LqbCJJe9h"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1oeudn8"}
									data-framer-name={"Heading"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"L8qVi8f3k"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={W88zB8mIG2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-kk6hck"}
											data-styles-preset={"SIbAeTqgh"}
										>
											{"What is Ametrix?"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-13ak2o1"}
									data-framer-name={"Plus"}
									layoutDependency={layoutDependency}
									layoutId={"BmjQy1aHN"}
									style={{
										backgroundColor:
											"var(--token-aa15e029-4bb1-434e-9852-151a8d809557, rgb(26, 26, 26))",
										borderBottomLeftRadius: "100%",
										borderBottomRightRadius: "100%",
										borderTopLeftRadius: "100%",
										borderTopRightRadius: "100%",
									}}
								>
									<motion.div
										className={"framer-5vkvpm"}
										layoutDependency={layoutDependency}
										layoutId={"FbZV74jhZ"}
										style={{
											backgroundColor:
												"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
											borderBottomLeftRadius: 10,
											borderBottomRightRadius: 10,
											borderTopLeftRadius: 10,
											borderTopRightRadius: 10,
											rotate: 45,
										}}
										variants={{
											lzZiJXpZ6: {
												backgroundColor:
													"var(--token-cecc2f3f-8752-4259-a9bd-b3a8dc815498, rgb(245, 245, 245))",
												rotate: 0,
											},
										}}
									/>
									<motion.div
										className={"framer-71e5al"}
										layoutDependency={layoutDependency}
										layoutId={"nN47C1t9I"}
										style={{
											backgroundColor:
												"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
											borderBottomLeftRadius: 10,
											borderBottomRightRadius: 10,
											borderTopLeftRadius: 10,
											borderTopRightRadius: 10,
											rotate: 45,
										}}
										variants={{
											lzZiJXpZ6: {
												backgroundColor:
													"var(--token-cecc2f3f-8752-4259-a9bd-b3a8dc815498, rgb(245, 245, 245))",
												rotate: 0,
											},
										}}
									/>
								</motion.div>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-e08tu2"}
									data-framer-name={"Line"}
									layoutDependency={layoutDependency}
									layoutId={"laJ8e9XdX"}
									style={{
										backgroundColor:
											"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									}}
								/>
							)}
							{isDisplayed() && (
								<motion.div
									className={"framer-bd37oi"}
									data-framer-name={"Answer"}
									layoutDependency={layoutDependency}
									layoutId={"O1LBUR639"}
									style={{
										filter: "blur(0px)",
										WebkitFilter: "blur(0px)",
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1mki6sd"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Gz4gVMTQx"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-9ff70694-0783-4e61-9f6a-7b939313b3bd, rgb(38, 38, 38))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={T8rQFvSBR2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1wiboy8"}
												data-styles-preset={"V8awtwKCk"}
												dir={"auto"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-9ff70694-0783-4e61-9f6a-7b939313b3bd, rgb(38, 38, 38)))",
												}}
											>
												{
													"Ametrix is an AI-powered inbox automation platform that drafts replies, schedules follow-ups, scores leads, and organizes email workflows so teams can move faster with less manual effort."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-MPW3t.framer-1cqrhv2, .framer-MPW3t .framer-1cqrhv2 { display: block; }",
	".framer-MPW3t.framer-14efhkn { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 400px; }",
	".framer-MPW3t .framer-hxm6di { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 24px 0px 24px 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-MPW3t .framer-1egiif8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 12px 0px 24px; position: relative; width: 100%; }",
	".framer-MPW3t .framer-1oeudn8 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-MPW3t .framer-13ak2o1 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 40px); overflow: hidden; position: relative; width: 40px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-MPW3t .framer-5vkvpm { flex: none; height: 2px; left: calc(50.00000000000002% - 14px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 14px; }",
	".framer-MPW3t .framer-71e5al { flex: none; height: 14px; left: calc(50.00000000000002% - 2px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 14px / 2); width: 2px; }",
	".framer-MPW3t .framer-e08tu2 { flex: none; height: 1px; overflow: visible; position: relative; width: 100%; }",
	".framer-MPW3t .framer-bd37oi { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 24px 0px 24px; position: relative; width: 100%; }",
	".framer-MPW3t .framer-1mki6sd { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 90%; word-break: break-word; word-wrap: break-word; }",
	".framer-MPW3t.framer-v-1fjwzoj .framer-hxm6di { padding: 12px 12px 12px 24px; }",
	".framer-MPW3t.framer-v-1fjwzoj .framer-1egiif8 { padding: 0px; }",
	...css,
	...css2,
];
var Framerf4N6Pei1z = withCSS(Component, css3, "framer-MPW3t");
var stdin_default = Framerf4N6Pei1z;
Framerf4N6Pei1z.displayName = "FAQ Card";
Framerf4N6Pei1z.defaultProps = {
	height: 249,
	width: 400,
};
addPropertyControls(Framerf4N6Pei1z, {
	variant: {
		options: ["IS4Ic9o6Y", "lzZiJXpZ6"],
		optionTitles: ["Open", "Closed"],
		title: "Variant",
		type: ControlType.Enum,
	},
	W88zB8mIG: {
		defaultValue: "What is Ametrix?",
		displayTextArea: true,
		title: "Question",
		type: ControlType.String,
	},
	T8rQFvSBR: {
		defaultValue:
			"Ametrix is an AI-powered inbox automation platform that drafts replies, schedules follow-ups, scores leads, and organizes email workflows so teams can move faster with less manual effort.",
		description: "",
		displayTextArea: true,
		title: "Answer",
		type: ControlType.String,
	},
});
addFonts(
	Framerf4N6Pei1z,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "IS4Ic9o6Y",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var faq_card_default = ComponentWithRoot;
export { faq_card_default as default };
