// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * click?: Function // Click
}} Props

 */
import {
	stdin_default as stdin_default3,
	stdin_default2 as stdin_default4,
	stdin_default3 as stdin_default5,
	stdin_default4 as stdin_default6,
	stdin_default5 as stdin_default7,
	stdin_default6 as stdin_default8,
	stdin_default7 as stdin_default9,
} from "./chunks/chunk-5T24GZYA.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-NW7LP6IH.js";
import { stdin_default } from "./chunks/chunk-XJ5QOGWX.js";
import "./chunks/chunk-6KOE3X73.js";
import "./chunks/chunk-DRXSNPA2.js";
import { routes } from "./chunks/chunk-643FN7SQ.js";

// virtual:nav-drop-down-container
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/aPNoFo289GZBz2UjTGAp/tm5HUoYKvDygfrcRdKDS/oA2pAvVBq.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ButtonSecondaryButtonFonts = getFonts(stdin_default2);
var serializationHash = "framer-TL0oq";
var variantClassNames = {
	eMq3jnee7: "framer-v-d52k9u",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		yVOka6jDE: click ?? props.yVOka6jDE,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		yVOka6jDE: yVOka6jDE2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "eMq3jnee7",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const acSpzGMGC7ongqg = activeVariantCallback(async (...args) => {
		if (yVOka6jDE2) {
			const res = await yVOka6jDE2(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-d52k9u",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"eMq3jnee7"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(255, 255, 255, 0.1)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(11px)",
							backgroundColor: "rgba(0, 0, 0, 0.85)",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							boxShadow:
								"0px 27px 26.299999237060547px 0px rgba(0, 0, 0, 0.16), 0px 4px 10px 0px rgba(0, 0, 0, 0.2), inset 0px 10px 39px 0px rgba(255, 255, 255, 0.25), 0px 0px 0px 1px var(--token-ba30b1fc-582a-4b3f-8242-3b762d615637, rgb(0, 0, 0))",
							WebkitBackdropFilter: "blur(11px)",
							...style,
						}}
					>
						<motion.div
							className={"framer-31wq2p"}
							data-framer-name={"Links Container"}
							layoutDependency={layoutDependency}
							layoutId={"O9MC5V_e7"}
						>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "Ai02WgZ_P",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks) => (
									<ComponentViewportProvider
										height={50}
										width={`calc(${componentViewport?.width || "100vw"} - 24px)`}
										y={
											(componentViewport?.y || 0) +
											12 +
											(((componentViewport?.height || 392) - 24 - 428) / 2 +
												0 +
												0) +
											0 +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-wyre44-container"}
											layoutDependency={layoutDependency}
											layoutId={"jWE9GOGsK-container"}
											nodeId={"jWE9GOGsK"}
											rendersWithMotion={true}
											scopeId={"oA2pAvVBq"}
										>
											{_jsx(stdin_default2, {
												acSpzGMGC: acSpzGMGC7ongqg,
												bLQDqyanN: stdin_default6,
												EvFOC7YXo: false,
												height: "100%",
												id: "jWE9GOGsK",
												J89Ucm84y: true,
												layoutId: "jWE9GOGsK",
												LyePqFSL3: "flex-start",
												QKqyYV11w: "rgba(255, 255, 255, 0)",
												rNXUHBS8V: resolvedLinks[0],
												style: {
													width: "100%",
												},
												variant: "FdRf7bWBO",
												WB6m_In3A: "Contact",
												width: "100%",
												Y6bbgR64g: "10px 16px 10px 16px",
												ZSfEeTznX: 1,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "zGhAaHm9M",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks1) => (
									<ComponentViewportProvider
										height={50}
										width={`calc(${componentViewport?.width || "100vw"} - 24px)`}
										y={
											(componentViewport?.y || 0) +
											12 +
											(((componentViewport?.height || 392) - 24 - 428) / 2 +
												0 +
												0) +
											0 +
											54
										}
									>
										<SmartComponentScopedContainer
											className={"framer-1e2hnl1-container"}
											layoutDependency={layoutDependency}
											layoutId={"B3EpDYavu-container"}
											nodeId={"B3EpDYavu"}
											rendersWithMotion={true}
											scopeId={"oA2pAvVBq"}
										>
											{_jsx(stdin_default2, {
												acSpzGMGC: acSpzGMGC7ongqg,
												bLQDqyanN: stdin_default7,
												EvFOC7YXo: false,
												height: "100%",
												id: "B3EpDYavu",
												J89Ucm84y: true,
												layoutId: "B3EpDYavu",
												LyePqFSL3: "flex-start",
												QKqyYV11w: "rgba(255, 255, 255, 0)",
												rNXUHBS8V: resolvedLinks1[0],
												style: {
													width: "100%",
												},
												variant: "FdRf7bWBO",
												WB6m_In3A: "Pricing",
												width: "100%",
												Y6bbgR64g: "10px 16px 10px 16px",
												ZSfEeTznX: 0.3,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "rqjL3v2I6",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks2) => (
									<ComponentViewportProvider
										height={50}
										width={`calc(${componentViewport?.width || "100vw"} - 24px)`}
										y={
											(componentViewport?.y || 0) +
											12 +
											(((componentViewport?.height || 392) - 24 - 428) / 2 +
												0 +
												0) +
											0 +
											108
										}
									>
										<SmartComponentScopedContainer
											className={"framer-15z4fgr-container"}
											layoutDependency={layoutDependency}
											layoutId={"d8rtW5a6x-container"}
											nodeId={"d8rtW5a6x"}
											rendersWithMotion={true}
											scopeId={"oA2pAvVBq"}
										>
											{_jsx(stdin_default2, {
												acSpzGMGC: acSpzGMGC7ongqg,
												bLQDqyanN: stdin_default3,
												EvFOC7YXo: false,
												height: "100%",
												id: "d8rtW5a6x",
												J89Ucm84y: true,
												layoutId: "d8rtW5a6x",
												LyePqFSL3: "flex-start",
												QKqyYV11w: "rgba(255, 255, 255, 0)",
												rNXUHBS8V: resolvedLinks2[0],
												style: {
													width: "100%",
												},
												variant: "FdRf7bWBO",
												WB6m_In3A: "Blogs",
												width: "100%",
												Y6bbgR64g: "10px 16px 10px 16px",
												ZSfEeTznX: 0.4,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "BbnwfmMeL",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks3) => (
									<ComponentViewportProvider
										height={50}
										width={`calc(${componentViewport?.width || "100vw"} - 24px)`}
										y={
											(componentViewport?.y || 0) +
											12 +
											(((componentViewport?.height || 392) - 24 - 428) / 2 +
												0 +
												0) +
											0 +
											162
										}
									>
										<SmartComponentScopedContainer
											className={"framer-1hum0qy-container"}
											layoutDependency={layoutDependency}
											layoutId={"paB8H93A_-container"}
											nodeId={"paB8H93A_"}
											rendersWithMotion={true}
											scopeId={"oA2pAvVBq"}
										>
											{_jsx(stdin_default2, {
												acSpzGMGC: acSpzGMGC7ongqg,
												bLQDqyanN: stdin_default,
												EvFOC7YXo: false,
												height: "100%",
												id: "paB8H93A_",
												J89Ucm84y: true,
												layoutId: "paB8H93A_",
												LyePqFSL3: "flex-start",
												QKqyYV11w: "rgba(255, 255, 255, 0)",
												rNXUHBS8V: resolvedLinks3[0],
												style: {
													width: "100%",
												},
												variant: "FdRf7bWBO",
												WB6m_In3A: "Waitlist",
												width: "100%",
												Y6bbgR64g: "10px 16px 10px 16px",
												ZSfEeTznX: 1,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "fQgil8iUm",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks4) => (
									<ComponentViewportProvider
										height={50}
										width={`calc(${componentViewport?.width || "100vw"} - 24px)`}
										y={
											(componentViewport?.y || 0) +
											12 +
											(((componentViewport?.height || 392) - 24 - 428) / 2 +
												0 +
												0) +
											0 +
											216
										}
									>
										<SmartComponentScopedContainer
											className={"framer-1ijvm6a-container"}
											layoutDependency={layoutDependency}
											layoutId={"hlNjkm9ek-container"}
											nodeId={"hlNjkm9ek"}
											rendersWithMotion={true}
											scopeId={"oA2pAvVBq"}
										>
											{_jsx(stdin_default2, {
												acSpzGMGC: acSpzGMGC7ongqg,
												bLQDqyanN: stdin_default5,
												EvFOC7YXo: false,
												height: "100%",
												id: "hlNjkm9ek",
												J89Ucm84y: true,
												layoutId: "hlNjkm9ek",
												LyePqFSL3: "flex-start",
												QKqyYV11w: "rgba(255, 255, 255, 0)",
												rNXUHBS8V: resolvedLinks4[0],
												style: {
													width: "100%",
												},
												variant: "FdRf7bWBO",
												WB6m_In3A: "Changelog",
												width: "100%",
												Y6bbgR64g: "10px 16px 10px 16px",
												ZSfEeTznX: 0.3,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "K8EUxnZHA",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks5) => (
									<ComponentViewportProvider
										height={50}
										width={`calc(${componentViewport?.width || "100vw"} - 24px)`}
										y={
											(componentViewport?.y || 0) +
											12 +
											(((componentViewport?.height || 392) - 24 - 428) / 2 +
												0 +
												0) +
											0 +
											270
										}
									>
										<SmartComponentScopedContainer
											className={"framer-1idnde4-container"}
											layoutDependency={layoutDependency}
											layoutId={"BfZJX6G5R-container"}
											nodeId={"BfZJX6G5R"}
											rendersWithMotion={true}
											scopeId={"oA2pAvVBq"}
										>
											{_jsx(stdin_default2, {
												acSpzGMGC: acSpzGMGC7ongqg,
												bLQDqyanN: stdin_default8,
												EvFOC7YXo: false,
												height: "100%",
												id: "BfZJX6G5R",
												J89Ucm84y: true,
												layoutId: "BfZJX6G5R",
												LyePqFSL3: "flex-start",
												QKqyYV11w: "rgba(255, 255, 255, 0)",
												rNXUHBS8V: resolvedLinks5[0],
												style: {
													width: "100%",
												},
												variant: "FdRf7bWBO",
												WB6m_In3A: "404",
												width: "100%",
												Y6bbgR64g: "10px 16px 10px 16px",
												ZSfEeTznX: 1,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											pathVariables: {
												gUfctbVHc: "terms-conditions",
											},
											unresolvedPathSlugs: {
												gUfctbVHc: {
													collectionId: "Le21BPsv9",
													collectionItemId: "qREnY17c3",
												},
											},
											webPageId: "h6yzSQHO2",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks6) => (
									<ComponentViewportProvider
										height={50}
										width={`calc(${componentViewport?.width || "100vw"} - 24px)`}
										y={
											(componentViewport?.y || 0) +
											12 +
											(((componentViewport?.height || 392) - 24 - 428) / 2 +
												0 +
												0) +
											0 +
											324
										}
									>
										<SmartComponentScopedContainer
											className={"framer-r0f8x1-container"}
											layoutDependency={layoutDependency}
											layoutId={"RBkzSEu__-container"}
											nodeId={"RBkzSEu__"}
											rendersWithMotion={true}
											scopeId={"oA2pAvVBq"}
										>
											{_jsx(stdin_default2, {
												acSpzGMGC: acSpzGMGC7ongqg,
												bLQDqyanN: stdin_default4,
												EvFOC7YXo: false,
												height: "100%",
												id: "RBkzSEu__",
												J89Ucm84y: true,
												layoutId: "RBkzSEu__",
												LyePqFSL3: "flex-start",
												QKqyYV11w: "rgba(255, 255, 255, 0)",
												rNXUHBS8V: resolvedLinks6[0],
												style: {
													width: "100%",
												},
												variant: "FdRf7bWBO",
												WB6m_In3A: "Terms & Conditions",
												width: "100%",
												Y6bbgR64g: "10px 16px 10px 16px",
												ZSfEeTznX: 0.4,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											pathVariables: {
												gUfctbVHc: "privacy-policy",
											},
											unresolvedPathSlugs: {
												gUfctbVHc: {
													collectionId: "Le21BPsv9",
													collectionItemId: "uvntoceej",
												},
											},
											webPageId: "h6yzSQHO2",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks7) => (
									<ComponentViewportProvider
										height={50}
										width={`calc(${componentViewport?.width || "100vw"} - 24px)`}
										y={
											(componentViewport?.y || 0) +
											12 +
											(((componentViewport?.height || 392) - 24 - 428) / 2 +
												0 +
												0) +
											0 +
											378
										}
									>
										<SmartComponentScopedContainer
											className={"framer-43azoa-container"}
											layoutDependency={layoutDependency}
											layoutId={"o6Y0PzGXz-container"}
											nodeId={"o6Y0PzGXz"}
											rendersWithMotion={true}
											scopeId={"oA2pAvVBq"}
										>
											{_jsx(stdin_default2, {
												acSpzGMGC: acSpzGMGC7ongqg,
												bLQDqyanN: stdin_default9,
												EvFOC7YXo: false,
												height: "100%",
												id: "o6Y0PzGXz",
												J89Ucm84y: true,
												layoutId: "o6Y0PzGXz",
												LyePqFSL3: "flex-start",
												QKqyYV11w: "rgba(255, 255, 255, 0)",
												rNXUHBS8V: resolvedLinks7[0],
												style: {
													width: "100%",
												},
												variant: "FdRf7bWBO",
												WB6m_In3A: "Privacy Policy",
												width: "100%",
												Y6bbgR64g: "10px 16px 10px 16px",
												ZSfEeTznX: 1,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TL0oq.framer-1lx5dnt, .framer-TL0oq .framer-1lx5dnt { display: block; }",
	".framer-TL0oq.framer-d52k9u { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 12px; position: relative; width: 206px; }",
	".framer-TL0oq .framer-31wq2p { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-TL0oq .framer-wyre44-container, .framer-TL0oq .framer-1e2hnl1-container, .framer-TL0oq .framer-15z4fgr-container, .framer-TL0oq .framer-1hum0qy-container, .framer-TL0oq .framer-1ijvm6a-container, .framer-TL0oq .framer-1idnde4-container, .framer-TL0oq .framer-r0f8x1-container, .framer-TL0oq .framer-43azoa-container { flex: none; height: auto; position: relative; width: 100%; }",
	'.framer-TL0oq[data-border="true"]::after, .framer-TL0oq [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FrameroA2pAvVBq = withCSS(Component, css, "framer-TL0oq");
var stdin_default10 = FrameroA2pAvVBq;
FrameroA2pAvVBq.displayName = "Nav Drop-Down Container";
FrameroA2pAvVBq.defaultProps = {
	height: 392,
	width: 206,
};
addPropertyControls(FrameroA2pAvVBq, {
	yVOka6jDE: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FrameroA2pAvVBq,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ButtonSecondaryButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:nav-drop-down-container
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default10, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavDropDownContainerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default10}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default10);
var nav_drop_down_container_default = ComponentWithRoot;
export { nav_drop_down_container_default as default };
