// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Open' | 'Close' // Variant
 * click?: Function // Click
 * hover?: Function // Hover
}} Props

 */
import { routes } from "./chunks/chunk-643FN7SQ.js";

// virtual:nav-trigger
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/5VmEZSK6jYdEA688G4sx/DRzJETw5jBuUbrXimEFS/h3whVDzN4.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["ADe__1Thl", "K_5IXzdaj"];
var serializationHash = "framer-hRwuw";
var variantClassNames = {
	ADe__1Thl: "framer-v-1d40xuq",
	K_5IXzdaj: "framer-v-1jdyjjn",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "K_5IXzdaj",
	Open: "ADe__1Thl",
};
var getProps = ({ click, height, hover, id, width, ...props }) => {
	return {
		...props,
		oTPInblsa: click ?? props.oTPInblsa,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ADe__1Thl",
		YAPMvZYgZ: hover ?? props.YAPMvZYgZ,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		oTPInblsa: oTPInblsa2,
		YAPMvZYgZ: YAPMvZYgZ2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ADe__1Thl",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapxf51cp = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (oTPInblsa2) {
			const res = await oTPInblsa2(...args);
			if (res === false) return false;
		}
	});
	const onMouseEnter18sym7d = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		if (YAPMvZYgZ2) {
			const res = await YAPMvZYgZ2(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "K_5IXzdaj") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1d40xuq",
							className,
							classNames,
						)}
						data-framer-name={"Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"ADe__1Thl"}
						onMouseEnter={onMouseEnter18sym7d}
						onTap={onTapxf51cp}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							boxShadow: "inset 0px 9px 19px 0px rgba(255, 255, 255, 0.25)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								K_5IXzdaj: {
									"data-framer-name": "Close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-19dvdaw"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"MCRJ_UWMR"}
						>
							<motion.div
								className={"framer-snxm64"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"lgHfsY_a8"}
								style={{
									backgroundColor:
										"var(--token-aa15e029-4bb1-434e-9852-151a8d809557, rgb(26, 26, 26))",
									borderBottomLeftRadius: 14,
									borderBottomRightRadius: 14,
									borderTopLeftRadius: 14,
									borderTopRightRadius: 14,
									rotate: 0,
								}}
								variants={{
									K_5IXzdaj: {
										rotate: 45,
									},
								}}
							/>
							{isDisplayed() && (
								<motion.div
									className={"framer-ew40bl"}
									data-framer-name={"Line"}
									layoutDependency={layoutDependency}
									layoutId={"pTucEoJVU"}
									style={{
										backgroundColor:
											"var(--token-aa15e029-4bb1-434e-9852-151a8d809557, rgb(26, 26, 26))",
										borderBottomLeftRadius: 14,
										borderBottomRightRadius: 14,
										borderTopLeftRadius: 14,
										borderTopRightRadius: 14,
									}}
								/>
							)}
							<motion.div
								className={"framer-1arbia5"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"CfiB1nRwT"}
								style={{
									backgroundColor:
										"var(--token-aa15e029-4bb1-434e-9852-151a8d809557, rgb(26, 26, 26))",
									borderBottomLeftRadius: 14,
									borderBottomRightRadius: 14,
									borderTopLeftRadius: 14,
									borderTopRightRadius: 14,
									rotate: 0,
								}}
								variants={{
									K_5IXzdaj: {
										rotate: -45,
									},
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-hRwuw.framer-72ekgc, .framer-hRwuw .framer-72ekgc { display: block; }",
	".framer-hRwuw.framer-1d40xuq { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 14px 20px 14px 20px; position: relative; width: min-content; }",
	".framer-hRwuw .framer-19dvdaw { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 24px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 24px; }",
	".framer-hRwuw .framer-snxm64 { flex: none; height: 2px; left: calc(50.00000000000002% - 18px / 2); overflow: visible; position: absolute; top: 6px; width: 18px; z-index: 1; }",
	".framer-hRwuw .framer-ew40bl { flex: none; height: 2px; left: calc(50.00000000000002% - 18px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 1.5px / 2); width: 18px; z-index: 1; }",
	".framer-hRwuw .framer-1arbia5 { bottom: 5px; flex: none; height: 2px; overflow: visible; position: absolute; right: 3px; width: 9px; z-index: 1; }",
	".framer-hRwuw.framer-v-1jdyjjn .framer-snxm64 { height: 2px; top: calc(50.00000000000002% - 2px / 2); }",
	".framer-hRwuw.framer-v-1jdyjjn .framer-1arbia5 { bottom: unset; height: 2px; top: calc(50.00000000000002% - 2px / 2); width: 18px; }",
];
var Framerh3whVDzN4 = withCSS(Component, css, "framer-hRwuw");
var stdin_default = Framerh3whVDzN4;
Framerh3whVDzN4.displayName = "Nav Trigger";
Framerh3whVDzN4.defaultProps = {
	height: 52,
	width: 64,
};
addPropertyControls(Framerh3whVDzN4, {
	variant: {
		options: ["ADe__1Thl", "K_5IXzdaj"],
		optionTitles: ["Open", "Close"],
		title: "Variant",
		type: ControlType.Enum,
	},
	oTPInblsa: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	YAPMvZYgZ: {
		title: "Hover",
		type: ControlType.EventHandler,
	},
});
addFonts(
	Framerh3whVDzN4,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:nav-trigger
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "K_5IXzdaj",
	xl: "ADe__1Thl",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavTriggerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var nav_trigger_default = ComponentWithRoot;
export { nav_trigger_default as default };
