// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Expanded' // Variant
 * click?: Function // Click
}} Props

 */
import { stdin_default as stdin_default4 } from "./chunks/chunk-NW7LP6IH.js";
import { stdin_default } from "./chunks/chunk-6KOE3X73.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-Z6E5IQ3K.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-GP3RWMYO.js";
import { className, css, fonts } from "./chunks/chunk-DRXSNPA2.js";
import { routes } from "./chunks/chunk-643FN7SQ.js";

// virtual:phone-drop-down-container
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6tzfd14oZnxgw1oXplac/ggJzNlOL3S9ZSyR5tbZi/rZwx4ADjk.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ArrowDropdownCaretSortSelectArrowFonts = getFonts(stdin_default2);
var ButtonSecondaryButtonFonts = getFonts(stdin_default4);
var ButtonPrimaryButtonFonts = getFonts(stdin_default3);
var cycleOrder = ["vf9MrkUq0", "ruKxA5SYc"];
var serializationHash = "framer-GKsI5";
var variantClassNames = {
	ruKxA5SYc: "framer-v-c5dr4r",
	vf9MrkUq0: "framer-v-1m7e1ag",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "vf9MrkUq0",
	Expanded: "ruKxA5SYc",
};
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "vf9MrkUq0",
		yBy8dOeb5: click ?? props.yBy8dOeb5,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		yBy8dOeb5: yBy8dOeb52,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "vf9MrkUq0",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap3qi1h0 = activeVariantCallback(async (...args) => {
		if (yBy8dOeb52) {
			const res = await yBy8dOeb52(...args);
			if (res === false) return false;
		}
	});
	const onTappj6lxd = activeVariantCallback(async (...args) => {
		setVariant("ruKxA5SYc");
	});
	const onTap11ru9yt = activeVariantCallback(async (...args) => {
		setVariant("vf9MrkUq0");
	});
	const acSpzGMGC3qi1h0 = activeVariantCallback(async (...args) => {
		if (yBy8dOeb52) {
			const res = await yBy8dOeb52(...args);
			if (res === false) return false;
		}
	});
	const puarA71qy3qi1h0 = activeVariantCallback(async (...args) => {
		if (yBy8dOeb52) {
			const res = await yBy8dOeb52(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "ruKxA5SYc") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "ruKxA5SYc") return true;
		return false;
	};
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1m7e1ag",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"vf9MrkUq0"}
						ref={refBinding}
						style={{
							backdropFilter: "blur(10px)",
							backgroundColor:
								"var(--token-ba30b1fc-582a-4b3f-8242-3b762d615637, rgb(0, 0, 0))",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							boxShadow:
								"0px 27px 26.299999237060547px 0px rgba(0, 0, 0, 0.16), 0px 4px 10px 0px rgba(0, 0, 0, 0.2)",
							WebkitBackdropFilter: "blur(10px)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								ruKxA5SYc: {
									"data-framer-name": "Expanded",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-17ogkh3"}
							data-framer-name={"Links Container"}
							layoutDependency={layoutDependency}
							layoutId={"Jrq9_EWy9"}
						>
							{isDisplayed() && (
								<Link
									href={{
										webPageId: "augiA20Il",
									}}
									motionChild={true}
									nodeId={"lKgsVh5j0"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-jqbz84 framer-hiyo74"}
										data-framer-name={"Navbar/Nav Link Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"lKgsVh5j0"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-ly1irt"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"dWBVq_AoG"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"Home"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
							{isDisplayed() && (
								<Link
									href={{
										webPageId: "zGhAaHm9M",
									}}
									motionChild={true}
									nodeId={"GfsYOjFDW"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-q4vihn framer-hiyo74"}
										data-framer-name={"Navbar/Nav Link Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"GfsYOjFDW"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-qc4q62"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"nZDFrlP8C"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"Pricing"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
							{isDisplayed() && (
								<Link
									href={{
										webPageId: "rqjL3v2I6",
									}}
									motionChild={true}
									nodeId={"s_0pTaTBQ"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-drwoz3 framer-hiyo74"}
										data-framer-name={"Navbar/Nav Link Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"s_0pTaTBQ"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-14chv96"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"jpqb2UeEU"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"Blogs"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
							{isDisplayed() && (
								<motion.div
									className={"framer-ipixgu"}
									data-framer-name={"Navbar/Nav Link Button"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"vtZNLgwhS"}
									onTap={onTappj6lxd}
									style={{
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-5f9q2g"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"zaBFHCK9u"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1dqim52"}
												data-styles-preset={"QowBsUafH"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
												}}
											>
												{"All Pages"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-1aauouv"}
										data-framer-name={"Icon Container"}
										layoutDependency={layoutDependency}
										layoutId={"o3AmzTxN5"}
									>
										{_jsx(stdin_default2, {
											animated: true,
											className: "framer-1e1q23e",
											layoutDependency,
											layoutId: "UbLn0_nFF",
											style: {
												"--1ww558a": 1.5,
												"--4rxgx6":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
											},
										})}
									</motion.div>
								</motion.div>
							)}
							{isDisplayed1() && (
								<motion.div
									className={"framer-1jnmm8u"}
									data-framer-name={"Navbar/Nav Link Button"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"xa99qgH7V"}
									onTap={onTap11ru9yt}
									style={{
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1gzg4hv"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ZvbwzFzYO"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1dqim52"}
												data-styles-preset={"QowBsUafH"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255)))",
												}}
											>
												{"All Pages"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-3n21vk"}
										data-framer-name={"Icon Container"}
										layoutDependency={layoutDependency}
										layoutId={"IYC8AFy5e"}
									>
										{_jsx(stdin_default2, {
											animated: true,
											className: "framer-1rv0c3h",
											layoutDependency,
											layoutId: "zc9mzXAXY",
											style: {
												"--1ww558a": 1.5,
												"--4rxgx6":
													"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
											},
										})}
									</motion.div>
								</motion.div>
							)}
							{isDisplayed1() && (
								<Link
									href={{
										webPageId: "Ai02WgZ_P",
									}}
									motionChild={true}
									nodeId={"V4tVgrayF"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-otq2u2 framer-hiyo74"}
										data-framer-name={"Button/Secondary Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"V4tVgrayF"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
											boxShadow:
												"0px 1px 1px 0px rgba(0, 0, 0, 0), 0px 3px 3px 0px rgba(0, 0, 0, 0), inset 0px 3px 12px 0px rgba(255, 255, 255, 0)",
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-557gxi"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"JreCqJ8zJ"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"Contact"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
							{isDisplayed1() && (
								<Link
									href={{
										webPageId: "zGhAaHm9M",
									}}
									motionChild={true}
									nodeId={"mTVZSIjQv"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-1hweh0 framer-hiyo74"}
										data-framer-name={"Button/Secondary Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"mTVZSIjQv"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
											boxShadow:
												"0px 1px 1px 0px rgba(0, 0, 0, 0), 0px 3px 3px 0px rgba(0, 0, 0, 0), inset 0px 3px 12px 0px rgba(255, 255, 255, 0)",
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-xxjv8g"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"WSSfgpfI3"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"Pricing"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
							{isDisplayed1() && (
								<Link
									href={{
										webPageId: "rqjL3v2I6",
									}}
									motionChild={true}
									nodeId={"X4bKVDcnQ"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-ngcf7z framer-hiyo74"}
										data-framer-name={"Button/Secondary Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"X4bKVDcnQ"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
											boxShadow:
												"0px 1px 1px 0px rgba(0, 0, 0, 0), 0px 3px 3px 0px rgba(0, 0, 0, 0), inset 0px 3px 12px 0px rgba(255, 255, 255, 0)",
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-yb8cq2"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"yDpRQ0Jrs"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"Blogs"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
							{isDisplayed1() && (
								<Link
									href={{
										webPageId: "BbnwfmMeL",
									}}
									motionChild={true}
									nodeId={"xl2YuL7NB"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-eox2k2 framer-hiyo74"}
										data-framer-name={"Button/Secondary Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"xl2YuL7NB"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
											boxShadow:
												"0px 1px 1px 0px rgba(0, 0, 0, 0), 0px 3px 3px 0px rgba(0, 0, 0, 0), inset 0px 3px 12px 0px rgba(255, 255, 255, 0)",
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1ddyons"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"YmAuzy3yu"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"Waitlist"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
							{isDisplayed1() && (
								<Link
									href={{
										webPageId: "fQgil8iUm",
									}}
									motionChild={true}
									nodeId={"LnYZn2w7M"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-1jcbv48 framer-hiyo74"}
										data-framer-name={"Button/Secondary Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"LnYZn2w7M"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
											boxShadow:
												"0px 1px 1px 0px rgba(0, 0, 0, 0), 0px 3px 3px 0px rgba(0, 0, 0, 0), inset 0px 3px 12px 0px rgba(255, 255, 255, 0)",
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-mnbsy2"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"LLKVIhm3O"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"Changelog"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
							{isDisplayed1() && (
								<Link
									href={{
										webPageId: "K8EUxnZHA",
									}}
									motionChild={true}
									nodeId={"S0emBYHHZ"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-1wjru2o framer-hiyo74"}
										data-framer-name={"Button/Secondary Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"S0emBYHHZ"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
											boxShadow:
												"0px 1px 1px 0px rgba(0, 0, 0, 0), 0px 3px 3px 0px rgba(0, 0, 0, 0), inset 0px 3px 12px 0px rgba(255, 255, 255, 0)",
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-11mo9yf"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"eQ65sSak9"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"404"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
							{isDisplayed1() && (
								<Link
									href={{
										pathVariables: {
											gUfctbVHc: "terms-conditions",
										},
										unresolvedPathSlugs: {
											gUfctbVHc: {
												collectionId: "Le21BPsv9",
												collectionItemId: "qREnY17c3",
											},
										},
										webPageId: "h6yzSQHO2",
									}}
									motionChild={true}
									nodeId={"wyZv_mXMY"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-1l0eos6 framer-hiyo74"}
										data-framer-name={"Button/Secondary Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"wyZv_mXMY"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
											boxShadow:
												"0px 1px 1px 0px rgba(0, 0, 0, 0), 0px 3px 3px 0px rgba(0, 0, 0, 0), inset 0px 3px 12px 0px rgba(255, 255, 255, 0)",
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1h79bu"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"qRT2grlSZ"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"Terms & Conditions"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
							{isDisplayed1() && (
								<Link
									href={{
										pathVariables: {
											gUfctbVHc: "privacy-policy",
										},
										unresolvedPathSlugs: {
											gUfctbVHc: {
												collectionId: "Le21BPsv9",
												collectionItemId: "uvntoceej",
											},
										},
										webPageId: "h6yzSQHO2",
									}}
									motionChild={true}
									nodeId={"yqW0hP2iw"}
									openInNewTab={false}
									scopeId={"rZwx4ADjk"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-1wyv760 framer-hiyo74"}
										data-framer-name={"Button/Secondary Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"yqW0hP2iw"}
										onTap={onTap3qi1h0}
										style={{
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
											boxShadow:
												"0px 1px 1px 0px rgba(0, 0, 0, 0), 0px 3px 3px 0px rgba(0, 0, 0, 0), inset 0px 3px 12px 0px rgba(255, 255, 255, 0)",
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-l4m6gq"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"ZG5WWbZ5f"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dqim52"}
													data-styles-preset={"QowBsUafH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88615e37-f88b-4d72-9af9-51da6ee30827, rgb(153, 153, 153)))",
													}}
												>
													{"Privacy Policy"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
							)}
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-19wp0y0"}
								data-framer-name={"Buttons Container"}
								layoutDependency={layoutDependency}
								layoutId={"ybStIUFgk"}
							>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "BbnwfmMeL",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks) => (
										<ComponentViewportProvider
											height={50}
											width={`calc(${componentViewport?.width || "100vw"} - 32px)`}
											y={
												(componentViewport?.y || 0) +
												20 +
												(((componentViewport?.height || 335) - 40 - 310) / 2 +
													182 +
													16) +
												0 +
												0
											}
										>
											<SmartComponentScopedContainer
												className={"framer-532pdw-container"}
												layoutDependency={layoutDependency}
												layoutId={"KEPRnVTmK-container"}
												nodeId={"KEPRnVTmK"}
												rendersWithMotion={true}
												scopeId={"rZwx4ADjk"}
											>
												{_jsx(stdin_default4, {
													acSpzGMGC: acSpzGMGC3qi1h0,
													bLQDqyanN: stdin_default,
													EvFOC7YXo: false,
													height: "100%",
													id: "KEPRnVTmK",
													J89Ucm84y: false,
													layoutId: "KEPRnVTmK",
													LyePqFSL3: "center",
													QKqyYV11w:
														"var(--token-aa15e029-4bb1-434e-9852-151a8d809557, rgb(26, 26, 26))",
													rNXUHBS8V: resolvedLinks[0],
													style: {
														width: "100%",
													},
													variant: "U2t_Okweq",
													WB6m_In3A: "Join Waitlist",
													width: "100%",
													Y6bbgR64g: "10px 16px 10px 16px",
													ZSfEeTznX: 1,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "Ai02WgZ_P",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks1) => (
										<ComponentViewportProvider
											height={52}
											width={`calc(${componentViewport?.width || "100vw"} - 32px)`}
											y={
												(componentViewport?.y || 0) +
												20 +
												(((componentViewport?.height || 335) - 40 - 310) / 2 +
													182 +
													16) +
												0 +
												60
											}
										>
											<SmartComponentScopedContainer
												className={"framer-i2dxql-container"}
												layoutDependency={layoutDependency}
												layoutId={"DDv8VTUGB-container"}
												nodeId={"DDv8VTUGB"}
												rendersWithMotion={true}
												scopeId={"rZwx4ADjk"}
											>
												{_jsx(stdin_default3, {
													height: "100%",
													id: "DDv8VTUGB",
													kxsr9hB1V: "Contact",
													layoutId: "DDv8VTUGB",
													m5s7pQQmA: resolvedLinks1[0],
													NHtMIEDfO: false,
													puarA71qy: puarA71qy3qi1h0,
													style: {
														width: "100%",
													},
													TX7nunh0I: "10px 14px 10px 14px",
													variant: "HE9WL3Va9",
													VteZZsIzV:
														"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
													width: "100%",
													ZueZHJx1j: true,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-GKsI5.framer-hiyo74, .framer-GKsI5 .framer-hiyo74 { display: block; }",
	".framer-GKsI5.framer-1m7e1ag { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 20px 16px 20px 16px; position: relative; width: 183px; }",
	".framer-GKsI5 .framer-17ogkh3 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-GKsI5 .framer-jqbz84, .framer-GKsI5 .framer-q4vihn, .framer-GKsI5 .framer-drwoz3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 10px 14px 10px 14px; position: relative; text-decoration: none; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-GKsI5 .framer-ly1irt, .framer-GKsI5 .framer-qc4q62, .framer-GKsI5 .framer-14chv96, .framer-GKsI5 .framer-5f9q2g, .framer-GKsI5 .framer-1gzg4hv, .framer-GKsI5 .framer-557gxi, .framer-GKsI5 .framer-xxjv8g, .framer-GKsI5 .framer-yb8cq2, .framer-GKsI5 .framer-1ddyons, .framer-GKsI5 .framer-mnbsy2, .framer-GKsI5 .framer-11mo9yf, .framer-GKsI5 .framer-1h79bu, .framer-GKsI5 .framer-l4m6gq { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-GKsI5 .framer-ipixgu, .framer-GKsI5 .framer-1jnmm8u { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 10px 14px 10px 14px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-GKsI5 .framer-1aauouv, .framer-GKsI5 .framer-3n21vk { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 22px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 22px; }",
	".framer-GKsI5 .framer-1e1q23e { flex: none; height: var(--framer-aspect-ratio-supported, 26px); position: relative; width: 26px; }",
	".framer-GKsI5 .framer-1rv0c3h { flex: none; height: var(--framer-aspect-ratio-supported, 27px); position: relative; width: 26px; }",
	".framer-GKsI5 .framer-otq2u2, .framer-GKsI5 .framer-1hweh0, .framer-GKsI5 .framer-ngcf7z, .framer-GKsI5 .framer-eox2k2, .framer-GKsI5 .framer-1jcbv48, .framer-GKsI5 .framer-1wjru2o, .framer-GKsI5 .framer-1l0eos6, .framer-GKsI5 .framer-1wyv760 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 10px 16px 10px 16px; position: relative; text-decoration: none; width: 100%; }",
	".framer-GKsI5 .framer-19wp0y0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-GKsI5 .framer-532pdw-container, .framer-GKsI5 .framer-i2dxql-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-GKsI5.framer-v-c5dr4r .framer-1jnmm8u { order: 4; }",
	".framer-GKsI5.framer-v-c5dr4r .framer-1rv0c3h { height: var(--framer-aspect-ratio-supported, 26px); }",
	".framer-GKsI5.framer-v-c5dr4r .framer-otq2u2 { order: 6; }",
	".framer-GKsI5.framer-v-c5dr4r .framer-1hweh0 { order: 5; }",
	".framer-GKsI5.framer-v-c5dr4r .framer-ngcf7z { order: 7; }",
	".framer-GKsI5.framer-v-c5dr4r .framer-eox2k2 { order: 8; }",
	".framer-GKsI5.framer-v-c5dr4r .framer-1jcbv48 { order: 9; }",
	".framer-GKsI5.framer-v-c5dr4r .framer-1wjru2o { order: 10; }",
	".framer-GKsI5.framer-v-c5dr4r .framer-1l0eos6 { order: 11; }",
	".framer-GKsI5.framer-v-c5dr4r .framer-1wyv760 { order: 12; }",
	...css,
];
var FramerrZwx4ADjk = withCSS(Component, css2, "framer-GKsI5");
var stdin_default5 = FramerrZwx4ADjk;
FramerrZwx4ADjk.displayName = "Phone Drop-Down Container";
FramerrZwx4ADjk.defaultProps = {
	height: 335,
	width: 183,
};
addPropertyControls(FramerrZwx4ADjk, {
	variant: {
		options: ["vf9MrkUq0", "ruKxA5SYc"],
		optionTitles: ["Default", "Expanded"],
		title: "Variant",
		type: ControlType.Enum,
	},
	yBy8dOeb5: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerrZwx4ADjk,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ArrowDropdownCaretSortSelectArrowFonts,
		...ButtonSecondaryButtonFonts,
		...ButtonPrimaryButtonFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:phone-drop-down-container
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "vf9MrkUq0",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PhoneDropDownContainerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var phone_drop_down_container_default = ComponentWithRoot;
export { phone_drop_down_container_default as default };
