// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
 * text?: string // Text
 * iconVisible?: boolean // Icon Visible
 * padding?: undefined // Padding
}} Props

 */
import { stdin_default } from "./chunks/chunk-GP3RWMYO.js";
import { className, css, fonts } from "./chunks/chunk-DRXSNPA2.js";
import { routes } from "./chunks/chunk-643FN7SQ.js";

// virtual:submit-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/FnpNyFaN2pmVfqgGxIpk/lufAodXTVhip872uZQM6/i7sKny_M7.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var ArrowDropdownCaretSortSelectArrowFonts = getFonts(stdin_default);
var enabledGestures = {
	aNGmwbDIb: {
		hover: true,
	},
};
var cycleOrder = [
	"aNGmwbDIb",
	"sZmX_KRix",
	"sLKlvcFy9",
	"yJwXKh61B",
	"WdplH171k",
];
var serializationHash = "framer-XE8gp";
var variantClassNames = {
	aNGmwbDIb: "framer-v-btyejg",
	sLKlvcFy9: "framer-v-1o4mspd",
	sZmX_KRix: "framer-v-xs6itq",
	WdplH171k: "framer-v-1j500c5",
	yJwXKh61B: "framer-v-1igpfrz",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var numberToPixelString = (value) => {
	if (typeof value !== "number") return value;
	if (!Number.isFinite(value)) return void 0;
	return Math.max(0, value) + "px";
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transformTemplate2 = (_, t) => `translateY(-50%) ${t}`;
var transformTemplate3 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "aNGmwbDIb",
	Disabled: "sLKlvcFy9",
	Error: "WdplH171k",
	Loading: "sZmX_KRix",
	Success: "yJwXKh61B",
};
var getProps = ({
	height,
	iconVisible,
	id,
	padding,
	text,
	width,
	...props
}) => {
	return {
		...props,
		aGTA4vrku: iconVisible ?? props.aGTA4vrku ?? true,
		KWffUjT0c: text ?? props.KWffUjT0c ?? "Start Free Trial",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "aNGmwbDIb",
		vQpoqqeCK: padding ?? props.vQpoqqeCK ?? "14px 13px 14px 14px",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		KWffUjT0c: KWffUjT0c2,
		aGTA4vrku: aGTA4vrku2,
		vQpoqqeCK: vQpoqqeCK2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "aNGmwbDIb",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "sZmX_KRix") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "sZmX_KRix") return false;
		return true;
	};
	const isDisplayed2 = (value) => {
		if (
			["sZmX_KRix", "sLKlvcFy9", "yJwXKh61B", "WdplH171k"].includes(baseVariant)
		)
			return false;
		return value;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.button
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-btyejg",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"aNGmwbDIb"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							opacity: 1,
							...style,
						}}
						variants={{
							"aNGmwbDIb-hover": {
								opacity: 1,
							},
							sLKlvcFy9: {
								opacity: 0.5,
							},
							WdplH171k: {
								opacity: 1,
							},
							yJwXKh61B: {
								opacity: 1,
							},
						}}
						{...addPropertyOverrides(
							{
								"aNGmwbDIb-hover": {
									"data-framer-name": void 0,
								},
								sLKlvcFy9: {
									"data-framer-name": "Disabled",
								},
								sZmX_KRix: {
									"data-framer-name": "Loading",
								},
								WdplH171k: {
									"data-framer-name": "Error",
								},
								yJwXKh61B: {
									"data-framer-name": "Success",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-twb4j5"}
							data-framer-name={"Dark"}
							layoutDependency={layoutDependency}
							layoutId={"IEDlfZ_RQ"}
							style={{
								backgroundColor:
									"var(--token-aa15e029-4bb1-434e-9852-151a8d809557, rgb(26, 26, 26))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								boxShadow:
									"0px 5px 12px 0px rgba(179, 179, 179, 0.1), 0px 21px 21px 0px rgba(179, 179, 179, 0.09), 0px 48px 29px 0px rgba(179, 179, 179, 0.05), 0px 86px 34px 0px rgba(179, 179, 179, 0.01), 0px 134px 38px 0px rgba(179, 179, 179, 0)",
							}}
							variants={{
								"aNGmwbDIb-hover": {
									backgroundColor:
										"var(--token-d2f1e252-5b0f-44d9-8028-2fd600944f65, rgb(255, 122, 0))",
									boxShadow:
										"0px 5px 12px 0px rgba(179, 179, 179, 0.1), 0px 21px 21px 0px rgba(179, 179, 179, 0.01), 0px 48px 29px 0px rgba(179, 179, 179, 0.05), 0px 86px 34px 0px rgba(179, 179, 179, 0.09), 0px 134px 38px 0px rgba(179, 179, 179, 0.1)",
								},
								WdplH171k: {
									backgroundColor: "rgb(204, 8, 8)",
								},
								yJwXKh61B: {
									backgroundColor: "rgb(7, 179, 27)",
								},
							}}
						>
							<motion.div
								className={"framer-u9y1sm"}
								data-border={true}
								data-framer-name={"Sub Container"}
								layoutDependency={layoutDependency}
								layoutId={"Efp8lm3hq"}
								style={{
									"--14hld8": numberToPixelString(vQpoqqeCK2),
									"--border-bottom-width": "0px",
									"--border-color": "rgba(255, 255, 255, 0.15)",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
									boxShadow:
										"0px 3px 6px 0px rgba(82, 82, 82, 0.1), 0px 10px 10px 0px rgba(82, 82, 82, 0.09), 0px 23px 14px 0px rgba(82, 82, 82, 0.05), 0px 40px 16px 0px rgba(82, 82, 82, 0.01), 0px 63px 18px 0px rgba(82, 82, 82, 0), inset 0px 1px 1px 0px rgba(255, 255, 255, 0.3), inset 0px 27px 30px 0px rgba(255, 255, 255, 0.1)",
								}}
								variants={{
									"aNGmwbDIb-hover": {
										boxShadow:
											"inset 0px 0px 10px 7px rgba(255, 255, 255, 0.15), 0px 0px 4px 3px rgba(255, 255, 255, 0.26), 0px 1px 1px 0px rgba(255, 255, 255, 0.3), 5px 135px 37px 0px rgba(210, 122, 40, 0.01), 3px 85px 34px 0px rgba(210, 122, 40, 0.02), inset 2px 48px 29px 0px rgba(210, 122, 40, 0.09), inset 1px 21px 21px 0px rgba(210, 122, 40, 0.09), 0px 5px 12px 0px rgba(210, 122, 40, 0.14)",
									},
								}}
							>
								{isDisplayed() && (
									<motion.div
										className={"framer-1beopss"}
										data-framer-name={"Spinner"}
										layoutDependency={layoutDependency}
										layoutId={"F1gOOOBjJ"}
										style={{
											mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
											WebkitMask:
												"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
										}}
									>
										<MotionDivWithFX
											__framer__loop={animation}
											__framer__loopEffectEnabled={true}
											__framer__loopRepeatDelay={0}
											__framer__loopRepeatType={"loop"}
											__framer__loopTransition={transition2}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1e1yimq"}
											data-framer-name={"Conic"}
											layoutDependency={layoutDependency}
											layoutId={"jW9ZM7_lt"}
											style={{
												backgroundColor: "rgb(204, 204, 204)",
											}}
										>
											<motion.div
												className={"framer-vamzzw"}
												data-framer-name={"Rounding"}
												layoutDependency={layoutDependency}
												layoutId={"p6eXUuYRG"}
												style={{
													backgroundColor: "rgb(204, 204, 204)",
													borderBottomLeftRadius: 1,
													borderBottomRightRadius: 1,
													borderTopLeftRadius: 1,
													borderTopRightRadius: 1,
												}}
												transformTemplate={transformTemplate1}
											/>
										</MotionDivWithFX>
									</motion.div>
								)}
								{isDisplayed1() && (
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1knbohw"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"qfq6JQet8"}
										style={{
											"--framer-paragraph-spacing": "0px",
											opacity: 1,
										}}
										text={KWffUjT0c2}
										variants={{
											"aNGmwbDIb-hover": {
												opacity: 1,
											},
											sLKlvcFy9: {
												opacity: 0.79,
											},
											WdplH171k: {
												opacity: 1,
											},
											yJwXKh61B: {
												opacity: 1,
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												WdplH171k: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1dqim52"}
																data-styles-preset={"QowBsUafH"}
															>
																{"Error"}
															</motion.p>
														</React.Fragment>
													),
													text: void 0,
												},
												yJwXKh61B: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1dqim52"}
																data-styles-preset={"QowBsUafH"}
															>
																{"Success"}
															</motion.p>
														</React.Fragment>
													),
													text: void 0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1dqim52"}
												data-styles-preset={"QowBsUafH"}
											>
												{"Start Free Trial"}
											</motion.p>
										</React.Fragment>
									</RichText>
								)}
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 38.5,
										intrinsicWidth: 111,
										pixelHeight: 77,
										pixelWidth: 222,
										src: "https://framerusercontent.com/images/CR4LOnTG56WK0VLDIDqWgOIG8pE.png?width=222&height=77",
									}}
									className={"framer-mr6mc9"}
									data-framer-name={"Abstract"}
									layoutDependency={layoutDependency}
									layoutId={"EF2KGTZfg"}
								/>
								{isDisplayed2(aGTA4vrku2 !== false) && (
									<motion.div
										className={"framer-nxhqnr"}
										data-framer-name={"Icon Container"}
										layoutDependency={layoutDependency}
										layoutId={"PJyzCRQo2"}
									>
										{_jsx(stdin_default, {
											animated: true,
											className: "framer-14fnkys",
											layoutDependency,
											layoutId: "Yynvls7vI",
											style: {
												"--1ww558a": 2.2,
												"--4rxgx6":
													"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
												rotate: -90,
											},
											transformTemplate: transformTemplate2,
											...addPropertyOverrides(
												{
													"aNGmwbDIb-hover": {
														transformTemplate: transformTemplate3,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
										{_jsx(stdin_default, {
											animated: true,
											className: "framer-k1f071",
											layoutDependency,
											layoutId: "NjZ8aSWdl",
											style: {
												"--1ww558a": 2.2,
												"--4rxgx6":
													"var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
												rotate: -90,
											},
											transformTemplate: transformTemplate3,
											...addPropertyOverrides(
												{
													"aNGmwbDIb-hover": {
														transformTemplate: transformTemplate2,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</motion.div>
								)}
							</motion.div>
						</motion.div>
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-XE8gp.framer-rljm2v, .framer-XE8gp .framer-rljm2v { display: block; }",
	".framer-XE8gp.framer-btyejg { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 150px; }",
	".framer-XE8gp .framer-twb4j5 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 1px; position: relative; width: 1px; }",
	".framer-XE8gp .framer-u9y1sm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: var(--14hld8); position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-XE8gp .framer-1beopss { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 21px); overflow: hidden; position: relative; width: 22px; }",
	".framer-XE8gp .framer-1e1yimq { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-XE8gp .framer-vamzzw { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	".framer-XE8gp .framer-1knbohw { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-XE8gp .framer-mr6mc9 { aspect-ratio: 2.8461538461538463 / 1; bottom: -1px; flex: none; left: -110px; overflow: visible; position: absolute; top: -1px; width: var(--framer-aspect-ratio-supported, 151px); z-index: 3; }",
	".framer-XE8gp .framer-nxhqnr { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 22px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 22px; }",
	".framer-XE8gp .framer-14fnkys { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 23px); left: -22px; position: absolute; top: 50%; width: 23px; z-index: 1; }",
	".framer-XE8gp .framer-k1f071 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 23px); left: 50%; position: absolute; top: 50%; width: 23px; z-index: 1; }",
	".framer-XE8gp.framer-v-xs6itq.framer-btyejg, .framer-XE8gp.framer-v-1o4mspd.framer-btyejg, .framer-XE8gp.framer-v-1igpfrz.framer-btyejg, .framer-XE8gp.framer-v-1j500c5.framer-btyejg { cursor: unset; }",
	".framer-XE8gp.framer-v-xs6itq .framer-1beopss { height: var(--framer-aspect-ratio-supported, 22px); }",
	".framer-XE8gp.framer-v-xs6itq .framer-mr6mc9 { width: var(--framer-aspect-ratio-supported, 150px); }",
	".framer-XE8gp.framer-v-btyejg.hover .framer-mr6mc9 { left: unset; right: -126px; }",
	".framer-XE8gp.framer-v-btyejg.hover .framer-14fnkys { left: 50%; }",
	".framer-XE8gp.framer-v-btyejg.hover .framer-k1f071 { left: 24px; }",
	...css,
	'.framer-XE8gp[data-border="true"]::after, .framer-XE8gp [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Frameri7sKny_M7 = withCSS(Component, css2, "framer-XE8gp");
var stdin_default2 = Frameri7sKny_M7;
Frameri7sKny_M7.displayName = "Submit Button";
Frameri7sKny_M7.defaultProps = {
	height: 52.5,
	width: 150,
};
addPropertyControls(Frameri7sKny_M7, {
	variant: {
		options: ["aNGmwbDIb", "sZmX_KRix", "sLKlvcFy9", "yJwXKh61B", "WdplH171k"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
	KWffUjT0c: {
		defaultValue: "Start Free Trial",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	aGTA4vrku: {
		defaultValue: true,
		title: "Icon Visible",
		type: ControlType.Boolean,
	},
	vQpoqqeCK: {
		defaultValue: "14px 13px 14px 14px",
		title: "Padding",
		type: ControlType.Padding,
	},
});
addFonts(
	Frameri7sKny_M7,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ArrowDropdownCaretSortSelectArrowFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:submit-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "aNGmwbDIb",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SubmitButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var submit_button_default = ComponentWithRoot;
export { submit_button_default as default };
