// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'In-Active' | 'Active' // Variant
}} Props

 */
import { stdin_default as stdin_default4 } from "../../chunks/chunk-DBQGJOYM.js";
import {
	stdin_default,
	stdin_default2 as stdin_default3,
} from "../../chunks/chunk-Q4MZ5JKT.js";
import { stdin_default as stdin_default2 } from "../../chunks/chunk-7TI3OG4T.js";
import "../../chunks/chunk-6KOE3X73.js";
import { className, css, fonts } from "../../chunks/chunk-QGLA3TUC.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../../chunks/chunk-SXEUHOLR.js";
import "../../chunks/chunk-UWDAN3I7.js";
import "../../chunks/chunk-DRXSNPA2.js";
import { routes } from "../../chunks/chunk-643FN7SQ.js";

// virtual:helper/pricing/tab-3
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/oxRTapiIv6NcTvT12UEv/PcstDARQP9Ae6NxrYeqj/UUsul2d45.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var HelperIconContainerFonts = getFonts(stdin_default2);
var ArrowSquareRightFonts = getFonts(stdin_default);
var HelperYesNoFonts = getFonts(stdin_default3);
var cycleOrder = ["ZfShIrIzQ", "JlK61GPwo"];
var serializationHash = "framer-kJN2u";
var variantClassNames = {
	JlK61GPwo: "framer-v-1xiu839",
	ZfShIrIzQ: "framer-v-1wd3o3e",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"In-Active": "ZfShIrIzQ",
	Active: "JlK61GPwo",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ZfShIrIzQ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ZfShIrIzQ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap7z46f1 = activeVariantCallback(async (...args) => {
		setVariant("JlK61GPwo");
	});
	const onTapxdkz08 = activeVariantCallback(async (...args) => {
		setVariant("ZfShIrIzQ");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1wd3o3e",
							className3,
							classNames,
						)}
						data-framer-name={"In-Active"}
						layoutDependency={layoutDependency}
						layoutId={"ZfShIrIzQ"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								JlK61GPwo: {
									"data-framer-name": "Active",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-uqnt0i"}
							data-framer-name={"Sub Container"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"ethBjaAIW"}
							onTap={onTap7z46f1}
							{...addPropertyOverrides(
								{
									JlK61GPwo: {
										onTap: onTapxdkz08,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<ComponentViewportProvider
								height={24}
								y={(componentViewport?.y || 0) + 0 + 0 + 25.5}
							>
								<SmartComponentScopedContainer
									className={"framer-1h58ps2-container"}
									layoutDependency={layoutDependency}
									layoutId={"UT2H0_pua-container"}
									nodeId={"UT2H0_pua"}
									rendersWithMotion={true}
									scopeId={"UUsul2d45"}
								>
									{_jsx(stdin_default2, {
										B8b2V9fZA: stdin_default4,
										E3bx3k8kp: 1.5,
										height: "100%",
										id: "UT2H0_pua",
										layoutId: "UT2H0_pua",
										pF3i9Z3QX: 1,
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1an6035"}
								data-framer-name={"Heading"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"QVGI3xFCq"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h6
										className={"framer-styles-preset-kk6hck"}
										data-styles-preset={"SIbAeTqgh"}
									>
										{"Analytics & Insights"}
									</motion.h6>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-1llsfxm"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"R6tEsCf_Q"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
							<motion.div
								className={"framer-149bb1s"}
								data-framer-name={"Icon Container"}
								layoutDependency={layoutDependency}
								layoutId={"BFs2TLOw4"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
								}}
							>
								{_jsx(stdin_default, {
									animated: true,
									className: "framer-6j3pw2",
									layoutDependency,
									layoutId: "Fl9ME5erB",
									style: {
										"--1m6trwb": 0,
										"--21h8s6":
											"var(--token-aa15e029-4bb1-434e-9852-151a8d809557, rgb(26, 26, 26))",
										"--pgex8v": 1.5,
										rotate: 90,
									},
									variants: {
										JlK61GPwo: {
											rotate: -90,
										},
									},
								})}
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-mlmddu"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"OVGIII2BY"}
							style={{
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								JlK61GPwo: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-1jdrquy"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"NoPeeEATP"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1h3xvht"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ZBQ1zhdbi"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Light Analytics"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-rv7zf5"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"NNOXYgr7a"}
							>
								<motion.div
									className={"framer-1iwgg72"}
									data-framer-name={"Frame 2147237649"}
									layoutDependency={layoutDependency}
									layoutId={"vs1HZXQmF"}
								>
									<motion.div
										className={"framer-ekrcep"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"OUT0WLfQ9"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 75 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-wapp3z-container"}
											layoutDependency={layoutDependency}
											layoutId={"Fk_Y0c_2t-container"}
											nodeId={"Fk_Y0c_2t"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "Fk_Y0c_2t",
												layoutId: "Fk_Y0c_2t",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-12wyxc7"}
									data-framer-name={"Frame 2147237646"}
									layoutDependency={layoutDependency}
									layoutId={"OaskMLF9K"}
								>
									<motion.div
										className={"framer-hjb3cf"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"MKc2QttfY"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-1h6q8co"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"dPkEGWpWF"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 75 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1t47lua-container"}
											layoutDependency={layoutDependency}
											layoutId={"YLrBpgxZr-container"}
											nodeId={"YLrBpgxZr"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "YLrBpgxZr",
												layoutId: "YLrBpgxZr",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-g762je"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"TPW88xioK"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 75 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1cxjswp-container"}
											layoutDependency={layoutDependency}
											layoutId={"GJTTQA_8r-container"}
											nodeId={"GJTTQA_8r"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "GJTTQA_8r",
												layoutId: "GJTTQA_8r",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1kpkxx0"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"eU2NY6eOQ"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-6izf7x"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"x6Suq67H8"}
							style={{
								backgroundColor: "rgb(242, 242, 242)",
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								JlK61GPwo: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-v76spc"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"dRvUtiRW4"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ykc033"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"lsIUxs0MG"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Full Analytics Dashboard"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-3lzmc1"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"B3PQP8VXf"}
							>
								<motion.div
									className={"framer-hy25be"}
									data-framer-name={"Frame 2147237648"}
									layoutDependency={layoutDependency}
									layoutId={"oWsXn6XCp"}
								>
									<motion.div
										className={"framer-r8x9wt"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"AvvFLze8F"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 141 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-hg56f9-container"}
											layoutDependency={layoutDependency}
											layoutId={"bdUyqIjvb-container"}
											nodeId={"bdUyqIjvb"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "bdUyqIjvb",
												layoutId: "bdUyqIjvb",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1g5i3gt"}
									data-framer-name={"Frame 2147237646"}
									layoutDependency={layoutDependency}
									layoutId={"XlZ4VwJBD"}
								>
									<motion.div
										className={"framer-1b3knb0"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"EHTZYmI6M"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-4dhzvh"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"wu8UQiMkn"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 141 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1ih4vw-container"}
											layoutDependency={layoutDependency}
											layoutId={"XdWk8Sx8K-container"}
											nodeId={"XdWk8Sx8K"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "XdWk8Sx8K",
												layoutId: "XdWk8Sx8K",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1n4pj9n"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"lqbzq8dql"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 141 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-14cdj18-container"}
											layoutDependency={layoutDependency}
											layoutId={"FR3TE79cJ-container"}
											nodeId={"FR3TE79cJ"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "FR3TE79cJ",
												layoutId: "FR3TE79cJ",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1yvrwtn"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"jnDxfNFAZ"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-2j5tuu"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"I3LGJnyVr"}
							style={{
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								JlK61GPwo: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-1663fw5"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"bXz2t9_PE"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-j23ctj"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"kmS9PDpv1"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Team Activity Insights"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-ejc8ov"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"drCUFVxLQ"}
							>
								<motion.div
									className={"framer-1dxve2y"}
									data-framer-name={"Frame 2147237648"}
									layoutDependency={layoutDependency}
									layoutId={"sj4MB13_R"}
								>
									<motion.div
										className={"framer-mr6dp7"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"r6FZ3ncua"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 207 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-85zefz-container"}
											layoutDependency={layoutDependency}
											layoutId={"oKJQDtdps-container"}
											nodeId={"oKJQDtdps"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "oKJQDtdps",
												layoutId: "oKJQDtdps",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1fb0urt"}
									data-framer-name={"Frame 2147237646"}
									layoutDependency={layoutDependency}
									layoutId={"v2UBp_FeT"}
								>
									<motion.div
										className={"framer-tzassk"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"BF_RrmoH8"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-inozo4"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"tmA_cPtx4"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 207 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-sjapr3-container"}
											layoutDependency={layoutDependency}
											layoutId={"Z1kfNnu6h-container"}
											nodeId={"Z1kfNnu6h"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "Z1kfNnu6h",
												layoutId: "Z1kfNnu6h",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-lelh7h"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"MyDGE99Iq"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 207 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-lg9q22-container"}
											layoutDependency={layoutDependency}
											layoutId={"BIKIyEvmB-container"}
											nodeId={"BIKIyEvmB"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "BIKIyEvmB",
												layoutId: "BIKIyEvmB",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1wxl64y"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"A_MFvOTWE"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-13mzx6e"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"XzVuICgbd"}
							style={{
								backgroundColor: "rgb(242, 242, 242)",
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								JlK61GPwo: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-1n94r5e"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"AiUD7KVhV"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1e2p54g"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"RrHriE39z"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Conversation Intelligence"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-i9fcdn"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"pVjzx0svX"}
							>
								<motion.div
									className={"framer-v3z58s"}
									data-framer-name={"Frame 2147237648"}
									layoutDependency={layoutDependency}
									layoutId={"KB0pDpKMo"}
								>
									<motion.div
										className={"framer-141n1tc"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"mBX6p25PK"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 273 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-hyjex1-container"}
											layoutDependency={layoutDependency}
											layoutId={"e0rgs7cYV-container"}
											nodeId={"e0rgs7cYV"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "e0rgs7cYV",
												layoutId: "e0rgs7cYV",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1afl0ki"}
									data-framer-name={"Frame 2147237649"}
									layoutDependency={layoutDependency}
									layoutId={"uiVNChDwa"}
								>
									<motion.div
										className={"framer-cjgj9e"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"lDwx4s63s"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-1crway6"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"kJCkHuWVl"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 273 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-q4zto7-container"}
											layoutDependency={layoutDependency}
											layoutId={"asDjUMtuB-container"}
											nodeId={"asDjUMtuB"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "asDjUMtuB",
												layoutId: "asDjUMtuB",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1ek50qc"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"Ld0z7tVEb"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 273 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1m2x3ie-container"}
											layoutDependency={layoutDependency}
											layoutId={"Wv5Bs2BuA-container"}
											nodeId={"Wv5Bs2BuA"}
											rendersWithMotion={true}
											scopeId={"UUsul2d45"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "Wv5Bs2BuA",
												layoutId: "Wv5Bs2BuA",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-187swd7"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"TJmsekVo_"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kJN2u.framer-3k2a75, .framer-kJN2u .framer-3k2a75 { display: block; }",
	".framer-kJN2u.framer-1wd3o3e { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 75px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1120px; }",
	".framer-kJN2u .framer-uqnt0i { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px 30px 24px 30px; position: relative; width: 100%; }",
	".framer-kJN2u .framer-1h58ps2-container, .framer-kJN2u .framer-wapp3z-container, .framer-kJN2u .framer-1t47lua-container, .framer-kJN2u .framer-1cxjswp-container, .framer-kJN2u .framer-hg56f9-container, .framer-kJN2u .framer-1ih4vw-container, .framer-kJN2u .framer-14cdj18-container, .framer-kJN2u .framer-85zefz-container, .framer-kJN2u .framer-sjapr3-container, .framer-kJN2u .framer-lg9q22-container, .framer-kJN2u .framer-hyjex1-container, .framer-kJN2u .framer-q4zto7-container, .framer-kJN2u .framer-1m2x3ie-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-kJN2u .framer-1an6035 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-kJN2u .framer-1llsfxm, .framer-kJN2u .framer-1kpkxx0, .framer-kJN2u .framer-1yvrwtn, .framer-kJN2u .framer-1wxl64y, .framer-kJN2u .framer-187swd7 { flex: none; height: 1px; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-kJN2u .framer-149bb1s { align-content: center; align-items: center; aspect-ratio: 1.3333333333333333 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 24px); justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 32px; will-change: var(--framer-will-change-override, transform); }",
	".framer-kJN2u .framer-6j3pw2 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 22px); position: relative; width: 22px; }",
	".framer-kJN2u .framer-mlmddu, .framer-kJN2u .framer-6izf7x, .framer-kJN2u .framer-2j5tuu, .framer-kJN2u .framer-13mzx6e { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-kJN2u .framer-1jdrquy, .framer-kJN2u .framer-v76spc, .framer-kJN2u .framer-1663fw5, .framer-kJN2u .framer-1n94r5e { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px 30px 20px 30px; position: relative; width: 342px; }",
	".framer-kJN2u .framer-1h3xvht, .framer-kJN2u .framer-ykc033, .framer-kJN2u .framer-j23ctj, .framer-kJN2u .framer-1e2p54g { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-kJN2u .framer-rv7zf5, .framer-kJN2u .framer-3lzmc1, .framer-kJN2u .framer-ejc8ov, .framer-kJN2u .framer-i9fcdn { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-kJN2u .framer-1iwgg72, .framer-kJN2u .framer-12wyxc7, .framer-kJN2u .framer-g762je, .framer-kJN2u .framer-hy25be, .framer-kJN2u .framer-1g5i3gt, .framer-kJN2u .framer-1n4pj9n, .framer-kJN2u .framer-1dxve2y, .framer-kJN2u .framer-1fb0urt, .framer-kJN2u .framer-lelh7h, .framer-kJN2u .framer-v3z58s, .framer-kJN2u .framer-1afl0ki, .framer-kJN2u .framer-1ek50qc { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: 66px; justify-content: center; overflow: visible; padding: 20px 30px 20px 30px; position: relative; width: 1px; }",
	".framer-kJN2u .framer-ekrcep, .framer-kJN2u .framer-hjb3cf, .framer-kJN2u .framer-r8x9wt, .framer-kJN2u .framer-1b3knb0, .framer-kJN2u .framer-mr6dp7, .framer-kJN2u .framer-tzassk, .framer-kJN2u .framer-141n1tc, .framer-kJN2u .framer-cjgj9e { bottom: 0px; flex: none; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 0px; width: 1px; z-index: 1; }",
	".framer-kJN2u .framer-1h6q8co, .framer-kJN2u .framer-4dhzvh, .framer-kJN2u .framer-inozo4, .framer-kJN2u .framer-1crway6 { bottom: 0px; flex: none; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; width: 1px; z-index: 1; }",
	".framer-kJN2u.framer-v-1xiu839.framer-1wd3o3e { height: min-content; }",
	...css2,
	...css,
];
var FramerUUsul2d45 = withCSS(Component, css3, "framer-kJN2u");
var stdin_default5 = FramerUUsul2d45;
FramerUUsul2d45.displayName = "Helper/Pricing/Tab-3";
FramerUUsul2d45.defaultProps = {
	height: 75,
	width: 1120,
};
addPropertyControls(FramerUUsul2d45, {
	variant: {
		options: ["ZfShIrIzQ", "JlK61GPwo"],
		optionTitles: ["In-Active", "Active"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerUUsul2d45,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...HelperIconContainerFonts,
		...ArrowSquareRightFonts,
		...HelperYesNoFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:helper/pricing/tab-3
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ZfShIrIzQ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Tab3FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var tab_3_default = ComponentWithRoot;
export { tab_3_default as default };
