// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'In-active' | 'Active' // Variant
}} Props

 */
import { stdin_default as stdin_default4 } from "../../chunks/chunk-4HTD7U2X.js";
import {
	stdin_default,
	stdin_default2 as stdin_default3,
} from "../../chunks/chunk-Q4MZ5JKT.js";
import { stdin_default as stdin_default2 } from "../../chunks/chunk-7TI3OG4T.js";
import "../../chunks/chunk-6KOE3X73.js";
import { className, css, fonts } from "../../chunks/chunk-QGLA3TUC.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../../chunks/chunk-SXEUHOLR.js";
import "../../chunks/chunk-UWDAN3I7.js";
import "../../chunks/chunk-DRXSNPA2.js";
import { routes } from "../../chunks/chunk-643FN7SQ.js";

// virtual:helper/pricing/tab-5
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jcuh3ZepBD4AoPrSsbrC/DzQ96TGax051pUBojSTT/pT1TE6eOK.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var HelperIconContainerFonts = getFonts(stdin_default2);
var ArrowSquareRightFonts = getFonts(stdin_default);
var HelperYesNoFonts = getFonts(stdin_default3);
var cycleOrder = ["e4LFh6SBH", "wxuawvG0b"];
var serializationHash = "framer-kT8R9";
var variantClassNames = {
	e4LFh6SBH: "framer-v-18jfkgl",
	wxuawvG0b: "framer-v-pm6oto",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"In-active": "e4LFh6SBH",
	Active: "wxuawvG0b",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "e4LFh6SBH",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "e4LFh6SBH",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap66rghy = activeVariantCallback(async (...args) => {
		setVariant("wxuawvG0b");
	});
	const onTap1aa13x2 = activeVariantCallback(async (...args) => {
		setVariant("e4LFh6SBH");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-18jfkgl",
							className3,
							classNames,
						)}
						data-framer-name={"In-active"}
						layoutDependency={layoutDependency}
						layoutId={"e4LFh6SBH"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								wxuawvG0b: {
									"data-framer-name": "Active",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1tpv8qi"}
							data-framer-name={"Sub Container"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"c55sXwFMf"}
							onTap={onTap66rghy}
							{...addPropertyOverrides(
								{
									wxuawvG0b: {
										onTap: onTap1aa13x2,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<ComponentViewportProvider
								height={24}
								y={(componentViewport?.y || 0) + 0 + 0 + 25.5}
							>
								<SmartComponentScopedContainer
									className={"framer-1s9mio-container"}
									layoutDependency={layoutDependency}
									layoutId={"qG0arWIz7-container"}
									nodeId={"qG0arWIz7"}
									rendersWithMotion={true}
									scopeId={"pT1TE6eOK"}
								>
									{_jsx(stdin_default2, {
										B8b2V9fZA: stdin_default4,
										E3bx3k8kp: 1.5,
										height: "100%",
										id: "qG0arWIz7",
										layoutId: "qG0arWIz7",
										pF3i9Z3QX: 1,
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1hmv7ru"}
								data-framer-name={"Heading"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"DN83g6zyo"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h6
										className={"framer-styles-preset-kk6hck"}
										data-styles-preset={"SIbAeTqgh"}
									>
										{"Team Collaboration"}
									</motion.h6>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-sda0qq"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"MlHevZ9Nh"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
							<motion.div
								className={"framer-36phhn"}
								data-framer-name={"Icon Container"}
								layoutDependency={layoutDependency}
								layoutId={"nVlY_Gsn5"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
								}}
							>
								{_jsx(stdin_default, {
									animated: true,
									className: "framer-oxfx74",
									layoutDependency,
									layoutId: "XBja2in1Z",
									style: {
										"--1m6trwb": 0,
										"--21h8s6":
											"var(--token-aa15e029-4bb1-434e-9852-151a8d809557, rgb(26, 26, 26))",
										"--pgex8v": 1.5,
										rotate: 90,
									},
									variants: {
										wxuawvG0b: {
											rotate: -90,
										},
									},
								})}
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-1u53zq5"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"tlOcFRWnV"}
							style={{
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								wxuawvG0b: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-jwkhqm"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"eWiMgWeka"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-i4j0r"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"MjqQfcRe0"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Community Support"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1sbijqa"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"BjWYlwdX8"}
							>
								<motion.div
									className={"framer-1tan4ch"}
									data-framer-name={"Frame 2147237649"}
									layoutDependency={layoutDependency}
									layoutId={"lPINZ3GNw"}
								>
									<motion.div
										className={"framer-isemas"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"m4wyVDZs5"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 75 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-175l6li-container"}
											layoutDependency={layoutDependency}
											layoutId={"QiOh5UcLs-container"}
											nodeId={"QiOh5UcLs"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "QiOh5UcLs",
												layoutId: "QiOh5UcLs",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-mknk99"}
									data-framer-name={"Frame 2147237646"}
									layoutDependency={layoutDependency}
									layoutId={"QrXVDx3AP"}
								>
									<motion.div
										className={"framer-a2g3j5"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"U0UF8ZvGv"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-pp7ueb"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"d8oVGbcY7"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 75 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-14z42by-container"}
											layoutDependency={layoutDependency}
											layoutId={"NDZYSPpGy-container"}
											nodeId={"NDZYSPpGy"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "NDZYSPpGy",
												layoutId: "NDZYSPpGy",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1pyc136"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"Yg0mPg1My"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 75 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-lvibco-container"}
											layoutDependency={layoutDependency}
											layoutId={"bGpdZ9ElO-container"}
											nodeId={"bGpdZ9ElO"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "bGpdZ9ElO",
												layoutId: "bGpdZ9ElO",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-63l2d0"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"OLOUFpuWX"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-133le3l"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"W2nSaib7x"}
							style={{
								backgroundColor: "rgb(242, 242, 242)",
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								wxuawvG0b: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-1r9ega8"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"HemVk6ylj"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-157p8ad"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"lZj502S1I"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Team Roles & Permissions"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1fyrrg2"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"KfP80lAmh"}
							>
								<motion.div
									className={"framer-p9lrc0"}
									data-framer-name={"Frame 2147237648"}
									layoutDependency={layoutDependency}
									layoutId={"OC3uJpKG8"}
								>
									<motion.div
										className={"framer-1i0xs5r"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"UeGKCIhtk"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 141 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1rvv8b9-container"}
											layoutDependency={layoutDependency}
											layoutId={"VmpwVoIFw-container"}
											nodeId={"VmpwVoIFw"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "VmpwVoIFw",
												layoutId: "VmpwVoIFw",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1ktuco1"}
									data-framer-name={"Frame 2147237649"}
									layoutDependency={layoutDependency}
									layoutId={"p2G7K4lXd"}
								>
									<motion.div
										className={"framer-1otaqno"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"XNohmU_AZ"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-jfrzyl"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"lkzfd3WLU"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 141 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-ke5qcb-container"}
											layoutDependency={layoutDependency}
											layoutId={"HBY4SEins-container"}
											nodeId={"HBY4SEins"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "HBY4SEins",
												layoutId: "HBY4SEins",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-579hjq"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"KJfFBpU8i"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 141 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-14z3u5c-container"}
											layoutDependency={layoutDependency}
											layoutId={"M86FK_R6d-container"}
											nodeId={"M86FK_R6d"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "M86FK_R6d",
												layoutId: "M86FK_R6d",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-mc4ixy"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"Qvrv2I8om"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-5ig767"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"WNb06gS6g"}
							style={{
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								wxuawvG0b: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-18oj1uw"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"rdwPrib04"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-12pp1su"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"D0UhxCaC_"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Shared Automations"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-woglpm"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"JN92Jx58c"}
							>
								<motion.div
									className={"framer-v5ltzy"}
									data-framer-name={"Frame 2147237648"}
									layoutDependency={layoutDependency}
									layoutId={"wSJL73rA9"}
								>
									<motion.div
										className={"framer-w2p9e3"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"eyp18Ttx6"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 207 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-j8afcr-container"}
											layoutDependency={layoutDependency}
											layoutId={"A_CFnwbwV-container"}
											nodeId={"A_CFnwbwV"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "A_CFnwbwV",
												layoutId: "A_CFnwbwV",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1nzsbaq"}
									data-framer-name={"Frame 2147237646"}
									layoutDependency={layoutDependency}
									layoutId={"uCBjAen8o"}
								>
									<motion.div
										className={"framer-3a33q5"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"dviP_37QV"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-upcsnw"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"oMkZEeZaK"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 207 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1os7t66-container"}
											layoutDependency={layoutDependency}
											layoutId={"MJ4oEW7gi-container"}
											nodeId={"MJ4oEW7gi"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "MJ4oEW7gi",
												layoutId: "MJ4oEW7gi",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-hlusju"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"AbHYXbGHV"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 207 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-bfmos7-container"}
											layoutDependency={layoutDependency}
											layoutId={"LU8chIHgV-container"}
											nodeId={"LU8chIHgV"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "LU8chIHgV",
												layoutId: "LU8chIHgV",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-jtnl5c"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"EQ9wgVlns"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-1ir9x7q"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"RoVCoU2rR"}
							style={{
								backgroundColor: "rgb(242, 242, 242)",
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								wxuawvG0b: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-7rnns5"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"APzMOJ_43"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-17507c0"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"U0PhFZC2K"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"SLA-Backed Support"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1x4lob6"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"vyyhBmPBo"}
							>
								<motion.div
									className={"framer-w285q1"}
									data-framer-name={"Frame 2147237648"}
									layoutDependency={layoutDependency}
									layoutId={"oL6sWdwwl"}
								>
									<motion.div
										className={"framer-17whdx5"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"uxPrTvqSC"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 273 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-jlvrac-container"}
											layoutDependency={layoutDependency}
											layoutId={"NKSROYrHz-container"}
											nodeId={"NKSROYrHz"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "NKSROYrHz",
												layoutId: "NKSROYrHz",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-185s5i7"}
									data-framer-name={"Frame 2147237649"}
									layoutDependency={layoutDependency}
									layoutId={"OCIYe0szq"}
								>
									<motion.div
										className={"framer-bluwxz"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"upFwPe0Ns"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-1wev0t3"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"fU6b0biD4"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 273 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1vur6au-container"}
											layoutDependency={layoutDependency}
											layoutId={"DYZIfYWAb-container"}
											nodeId={"DYZIfYWAb"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "DYZIfYWAb",
												layoutId: "DYZIfYWAb",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1xmikby"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"GPbfSKqrb"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 273 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-91b0q0-container"}
											layoutDependency={layoutDependency}
											layoutId={"v4nuHYZyf-container"}
											nodeId={"v4nuHYZyf"}
											rendersWithMotion={true}
											scopeId={"pT1TE6eOK"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "v4nuHYZyf",
												layoutId: "v4nuHYZyf",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-cy51vu"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"q0wUge8on"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kT8R9.framer-1rsy95d, .framer-kT8R9 .framer-1rsy95d { display: block; }",
	".framer-kT8R9.framer-18jfkgl { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 75px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1120px; }",
	".framer-kT8R9 .framer-1tpv8qi { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px 30px 24px 30px; position: relative; width: 100%; }",
	".framer-kT8R9 .framer-1s9mio-container, .framer-kT8R9 .framer-175l6li-container, .framer-kT8R9 .framer-14z42by-container, .framer-kT8R9 .framer-lvibco-container, .framer-kT8R9 .framer-1rvv8b9-container, .framer-kT8R9 .framer-ke5qcb-container, .framer-kT8R9 .framer-14z3u5c-container, .framer-kT8R9 .framer-j8afcr-container, .framer-kT8R9 .framer-1os7t66-container, .framer-kT8R9 .framer-bfmos7-container, .framer-kT8R9 .framer-jlvrac-container, .framer-kT8R9 .framer-1vur6au-container, .framer-kT8R9 .framer-91b0q0-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-kT8R9 .framer-1hmv7ru { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-kT8R9 .framer-sda0qq, .framer-kT8R9 .framer-63l2d0, .framer-kT8R9 .framer-mc4ixy, .framer-kT8R9 .framer-jtnl5c, .framer-kT8R9 .framer-cy51vu { flex: none; height: 1px; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-kT8R9 .framer-36phhn { align-content: center; align-items: center; aspect-ratio: 1.3333333333333333 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 24px); justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 32px; will-change: var(--framer-will-change-override, transform); }",
	".framer-kT8R9 .framer-oxfx74 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 22px); position: relative; width: 22px; }",
	".framer-kT8R9 .framer-1u53zq5, .framer-kT8R9 .framer-133le3l, .framer-kT8R9 .framer-5ig767, .framer-kT8R9 .framer-1ir9x7q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-kT8R9 .framer-jwkhqm, .framer-kT8R9 .framer-1r9ega8, .framer-kT8R9 .framer-18oj1uw, .framer-kT8R9 .framer-7rnns5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px 30px 20px 30px; position: relative; width: 342px; }",
	".framer-kT8R9 .framer-i4j0r, .framer-kT8R9 .framer-157p8ad, .framer-kT8R9 .framer-12pp1su, .framer-kT8R9 .framer-17507c0 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-kT8R9 .framer-1sbijqa, .framer-kT8R9 .framer-1fyrrg2, .framer-kT8R9 .framer-woglpm, .framer-kT8R9 .framer-1x4lob6 { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-kT8R9 .framer-1tan4ch, .framer-kT8R9 .framer-mknk99, .framer-kT8R9 .framer-1pyc136, .framer-kT8R9 .framer-p9lrc0, .framer-kT8R9 .framer-1ktuco1, .framer-kT8R9 .framer-579hjq, .framer-kT8R9 .framer-v5ltzy, .framer-kT8R9 .framer-1nzsbaq, .framer-kT8R9 .framer-hlusju, .framer-kT8R9 .framer-w285q1, .framer-kT8R9 .framer-185s5i7, .framer-kT8R9 .framer-1xmikby { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: 66px; justify-content: center; overflow: visible; padding: 20px 30px 20px 30px; position: relative; width: 1px; }",
	".framer-kT8R9 .framer-isemas, .framer-kT8R9 .framer-a2g3j5, .framer-kT8R9 .framer-1i0xs5r, .framer-kT8R9 .framer-1otaqno, .framer-kT8R9 .framer-w2p9e3, .framer-kT8R9 .framer-3a33q5, .framer-kT8R9 .framer-17whdx5, .framer-kT8R9 .framer-bluwxz { bottom: 0px; flex: none; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 0px; width: 1px; z-index: 1; }",
	".framer-kT8R9 .framer-pp7ueb, .framer-kT8R9 .framer-jfrzyl, .framer-kT8R9 .framer-upcsnw, .framer-kT8R9 .framer-1wev0t3 { bottom: 0px; flex: none; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; width: 1px; z-index: 1; }",
	".framer-kT8R9.framer-v-pm6oto.framer-18jfkgl { height: min-content; }",
	...css2,
	...css,
];
var FramerpT1TE6eOK = withCSS(Component, css3, "framer-kT8R9");
var stdin_default5 = FramerpT1TE6eOK;
FramerpT1TE6eOK.displayName = "Helper/Pricing/Tab-5";
FramerpT1TE6eOK.defaultProps = {
	height: 75,
	width: 1120,
};
addPropertyControls(FramerpT1TE6eOK, {
	variant: {
		options: ["e4LFh6SBH", "wxuawvG0b"],
		optionTitles: ["In-active", "Active"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerpT1TE6eOK,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...HelperIconContainerFonts,
		...ArrowSquareRightFonts,
		...HelperYesNoFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:helper/pricing/tab-5
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "e4LFh6SBH",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Tab5FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var tab_5_default = ComponentWithRoot;
export { tab_5_default as default };
