// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 290dfde5ba1ea706 "Ametrix (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'In-Active' | 'Active' // Variant
}} Props

 */
import {
	stdin_default as stdin_default2,
	stdin_default2 as stdin_default4,
} from "../../chunks/chunk-Q4MZ5JKT.js";
import { stdin_default as stdin_default3 } from "../../chunks/chunk-7TI3OG4T.js";
import { stdin_default } from "../../chunks/chunk-6KOE3X73.js";
import { className, css, fonts } from "../../chunks/chunk-QGLA3TUC.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../../chunks/chunk-SXEUHOLR.js";
import "../../chunks/chunk-UWDAN3I7.js";
import "../../chunks/chunk-DRXSNPA2.js";
import { routes } from "../../chunks/chunk-643FN7SQ.js";

// virtual:helper/pricing/tab-1
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/5P4TPu2DCc7T3q9DXHoz/8dkzIzGObsJCfMFa5kpW/Aq87HMUf_.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var HelperIconContainerFonts = getFonts(stdin_default3);
var ArrowSquareRightFonts = getFonts(stdin_default2);
var HelperYesNoFonts = getFonts(stdin_default4);
var cycleOrder = ["yaH3MSkbn", "XXYH9pKW3"];
var serializationHash = "framer-wyJxC";
var variantClassNames = {
	XXYH9pKW3: "framer-v-712fq6",
	yaH3MSkbn: "framer-v-1yisz4f",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"In-Active": "yaH3MSkbn",
	Active: "XXYH9pKW3",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "yaH3MSkbn",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "yaH3MSkbn",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTaprrfzo5 = activeVariantCallback(async (...args) => {
		setVariant("XXYH9pKW3");
	});
	const onTapxvxig4 = activeVariantCallback(async (...args) => {
		setVariant("yaH3MSkbn");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1yisz4f",
							className3,
							classNames,
						)}
						data-framer-name={"In-Active"}
						layoutDependency={layoutDependency}
						layoutId={"yaH3MSkbn"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								XXYH9pKW3: {
									"data-framer-name": "Active",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1s47ypg"}
							data-framer-name={"Sub Container"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"aaqS5CItO"}
							onTap={onTaprrfzo5}
							{...addPropertyOverrides(
								{
									XXYH9pKW3: {
										onTap: onTapxvxig4,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<ComponentViewportProvider
								height={24}
								y={(componentViewport?.y || 0) + 0 + 0 + 25.5}
							>
								<SmartComponentScopedContainer
									className={"framer-12byxbu-container"}
									layoutDependency={layoutDependency}
									layoutId={"APAXTQ7bk-container"}
									nodeId={"APAXTQ7bk"}
									rendersWithMotion={true}
									scopeId={"Aq87HMUf_"}
								>
									{_jsx(stdin_default3, {
										B8b2V9fZA: stdin_default,
										E3bx3k8kp: 1.5,
										height: "100%",
										id: "APAXTQ7bk",
										layoutId: "APAXTQ7bk",
										pF3i9Z3QX: 1,
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-13fh5ot"}
								data-framer-name={"Heading"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ddcO4hSsF"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h6
										className={"framer-styles-preset-kk6hck"}
										data-styles-preset={"SIbAeTqgh"}
									>
										{"Smart Inbox"}
									</motion.h6>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-181m3s4"}
								data-framer-name={"Icon Container"}
								layoutDependency={layoutDependency}
								layoutId={"FxnImtmgd"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
								}}
							>
								{_jsx(stdin_default2, {
									animated: true,
									className: "framer-ks72dj",
									layoutDependency,
									layoutId: "TKqpHujel",
									style: {
										"--1m6trwb": 0,
										"--21h8s6":
											"var(--token-aa15e029-4bb1-434e-9852-151a8d809557, rgb(26, 26, 26))",
										"--pgex8v": 1.5,
										rotate: 90,
									},
									variants: {
										XXYH9pKW3: {
											rotate: -90,
										},
									},
								})}
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-17omepw"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"aOLrRmEoV"}
							style={{
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								XXYH9pKW3: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-19y1uoe"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"Mr2EMedhy"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-gdyjey"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"RWLBFHwlb"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"AI Smart Replies"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-2fj8nq"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"QtzbdGOJj"}
							>
								<motion.div
									className={"framer-qp12jt"}
									data-framer-name={"Frame 2147237642"}
									layoutDependency={layoutDependency}
									layoutId={"RURNwbH_f"}
								>
									<motion.div
										className={"framer-1hjzuti"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"T5vEFMBDl"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 75 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1v4tmp3-container"}
											layoutDependency={layoutDependency}
											layoutId={"d1Bcg64s7-container"}
											nodeId={"d1Bcg64s7"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "d1Bcg64s7",
												layoutId: "d1Bcg64s7",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1jp98bf"}
									data-framer-name={"Frame 2147237646"}
									layoutDependency={layoutDependency}
									layoutId={"Xf8B6ZoEx"}
								>
									<motion.div
										className={"framer-b3s765"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"JoW19mPeI"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-h8von7"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"ntVsXjsVd"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 75 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-gp8xkx-container"}
											layoutDependency={layoutDependency}
											layoutId={"J4JMO24Jw-container"}
											nodeId={"J4JMO24Jw"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "J4JMO24Jw",
												layoutId: "J4JMO24Jw",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1l2pheh"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"bFejtqGDh"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 75 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1oc305r-container"}
											layoutDependency={layoutDependency}
											layoutId={"X5DihT6_L-container"}
											nodeId={"X5DihT6_L"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "X5DihT6_L",
												layoutId: "X5DihT6_L",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-q540yk"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"JAkg6QnkC"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-1n6oe0w"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"iTsucv7FG"}
							style={{
								backgroundColor: "rgb(242, 242, 242)",
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								XXYH9pKW3: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-qackod"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"diXddF7nB"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1jmmx7t"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"whDDejtxv"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Priority Inbox Sorting"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-10gbgn0"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"IlEnAi05F"}
							>
								<motion.div
									className={"framer-yix7h8"}
									data-framer-name={"Frame 2147237642"}
									layoutDependency={layoutDependency}
									layoutId={"JE8ak3a3r"}
								>
									<motion.div
										className={"framer-icbhoy"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"U7aIgHd2Y"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 141 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-42fto3-container"}
											layoutDependency={layoutDependency}
											layoutId={"pCXwLfTFk-container"}
											nodeId={"pCXwLfTFk"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "pCXwLfTFk",
												layoutId: "pCXwLfTFk",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1pno2ad"}
									data-framer-name={"Frame 2147237646"}
									layoutDependency={layoutDependency}
									layoutId={"Wy_CLUpNc"}
								>
									<motion.div
										className={"framer-1qvc6g4"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"rUBGGwm7z"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-n8qney"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"YFXmI66Mw"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 141 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-18jmqxk-container"}
											layoutDependency={layoutDependency}
											layoutId={"sjC1aPDzr-container"}
											nodeId={"sjC1aPDzr"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "sjC1aPDzr",
												layoutId: "sjC1aPDzr",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1yzxcde"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"vbWnIgGVe"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 141 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1etrq84-container"}
											layoutDependency={layoutDependency}
											layoutId={"Dc6oEqgyq-container"}
											nodeId={"Dc6oEqgyq"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "Dc6oEqgyq",
												layoutId: "Dc6oEqgyq",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-12qhe31"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"c_O40GAFL"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-1n6i4m0"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"yqUCbitQv"}
							style={{
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								XXYH9pKW3: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-x69vqi"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"t06u7woUb"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-qbpfeo"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"zkLLUWX_c"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Basic Follow-up Nudges"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-qrizvl"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"DXf0AKalR"}
							>
								<motion.div
									className={"framer-1rw4s64"}
									data-framer-name={"Frame 2147237642"}
									layoutDependency={layoutDependency}
									layoutId={"RxcaXutzU"}
								>
									<motion.div
										className={"framer-fwauws"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"lpOnc5myW"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 207 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1uo6f59-container"}
											layoutDependency={layoutDependency}
											layoutId={"N2Pc92nMY-container"}
											nodeId={"N2Pc92nMY"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "N2Pc92nMY",
												layoutId: "N2Pc92nMY",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-qixe0h"}
									data-framer-name={"Frame 2147237646"}
									layoutDependency={layoutDependency}
									layoutId={"Y5KSaYI1C"}
								>
									<motion.div
										className={"framer-1qphyvy"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"s99t0uu72"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-n797kq"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"N_tSeZ4Zr"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 207 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-iln9ja-container"}
											layoutDependency={layoutDependency}
											layoutId={"uheP7LsA8-container"}
											nodeId={"uheP7LsA8"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "uheP7LsA8",
												layoutId: "uheP7LsA8",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-f5qts4"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"w0zSBvfS6"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 207 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-cer9h4-container"}
											layoutDependency={layoutDependency}
											layoutId={"PVv24ij9U-container"}
											nodeId={"PVv24ij9U"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "PVv24ij9U",
												layoutId: "PVv24ij9U",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-xc9s23"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"dTpWMJBAL"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-vdragp"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"nGdB2uP_S"}
							style={{
								backgroundColor: "rgb(242, 242, 242)",
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								XXYH9pKW3: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-10oukxz"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"t6vor4vbP"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1rfnokh"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"R7HXSVxkx"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Multi-channel Sync (Email only)"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-ta4s95"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"fLReMwaRw"}
							>
								<motion.div
									className={"framer-15iw5xz"}
									data-framer-name={"Frame 2147237642"}
									layoutDependency={layoutDependency}
									layoutId={"iUDTlJxPP"}
								>
									<motion.div
										className={"framer-1g27d52"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"XaEp9eOVT"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 273 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-12dqk1c-container"}
											layoutDependency={layoutDependency}
											layoutId={"pZpjnT98s-container"}
											nodeId={"pZpjnT98s"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "pZpjnT98s",
												layoutId: "pZpjnT98s",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1d5twln"}
									data-framer-name={"Frame 2147237646"}
									layoutDependency={layoutDependency}
									layoutId={"UxT79w6lM"}
								>
									<motion.div
										className={"framer-1kqsuv"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"uS45PZ6rH"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-w1q08y"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"UFH0npuue"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 273 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-hfydsd-container"}
											layoutDependency={layoutDependency}
											layoutId={"RepA7dVT3-container"}
											nodeId={"RepA7dVT3"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "RepA7dVT3",
												layoutId: "RepA7dVT3",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-6k4477"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"MlsTjw6P1"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 273 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-wudjoc-container"}
											layoutDependency={layoutDependency}
											layoutId={"hcaDL2yjK-container"}
											nodeId={"hcaDL2yjK"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "hcaDL2yjK",
												layoutId: "hcaDL2yjK",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-11514mp"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"trqCeNeu5"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-105aogb"}
							data-framer-name={"Sub Container"}
							layoutDependency={layoutDependency}
							layoutId={"V0l2GSrTS"}
							style={{
								filter: "blur(5px)",
								opacity: 0,
								WebkitFilter: "blur(5px)",
							}}
							variants={{
								XXYH9pKW3: {
									filter: "blur(0px)",
									opacity: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<motion.div
								className={"framer-1j1rklo"}
								data-framer-name={"Frame 2147237641"}
								layoutDependency={layoutDependency}
								layoutId={"xY1eQHAmR"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-yapi9k"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"yeYLFgFAQ"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1est8a"}
											data-styles-preset={"dJk2BbTAu"}
										>
											{"Extended Multi-Channel"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1i9uevj"}
								data-framer-name={"Frame 2147237647"}
								layoutDependency={layoutDependency}
								layoutId={"Cc8wiW9rq"}
							>
								<motion.div
									className={"framer-lxlj5f"}
									data-framer-name={"Frame 2147237648"}
									layoutDependency={layoutDependency}
									layoutId={"SvDOaMyGH"}
								>
									<motion.div
										className={"framer-1dbzu6h"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"XD8ESgj_K"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 339 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-1oazxc-container"}
											layoutDependency={layoutDependency}
											layoutId={"my4k8632b-container"}
											nodeId={"my4k8632b"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "my4k8632b",
												layoutId: "my4k8632b",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1qaace8"}
									data-framer-name={"Frame 2147237647"}
									layoutDependency={layoutDependency}
									layoutId={"yT97_3zvG"}
								>
									<motion.div
										className={"framer-109n1ir"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"dTYDbsj4O"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<motion.div
										className={"framer-113cqfu"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"bhTtu_GG_"}
										style={{
											backgroundColor:
												"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
											boxShadow:
												"1px 0px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
										}}
									/>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 339 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-11g1lyv-container"}
											layoutDependency={layoutDependency}
											layoutId={"Yv55nRqPa-container"}
											nodeId={"Yv55nRqPa"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "Yv55nRqPa",
												layoutId: "Yv55nRqPa",
												variant: matchVariant("nsD3ZP7ld"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1jmjh16"}
									data-framer-name={"Frame 2147237645"}
									layoutDependency={layoutDependency}
									layoutId={"iQ3F8pe1U"}
								>
									<ComponentViewportProvider
										height={22}
										y={(componentViewport?.y || 0) + 0 + 339 + 0 + 0 + 0 + 22}
									>
										<SmartComponentScopedContainer
											className={"framer-n27hbi-container"}
											layoutDependency={layoutDependency}
											layoutId={"HtQK8Pu0r-container"}
											nodeId={"HtQK8Pu0r"}
											rendersWithMotion={true}
											scopeId={"Aq87HMUf_"}
										>
											{_jsx(stdin_default4, {
												height: "100%",
												id: "HtQK8Pu0r",
												layoutId: "HtQK8Pu0r",
												variant: matchVariant("hdLcwNLoJ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1b1clqo"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"tDwekwfj4"}
								style={{
									backgroundColor:
										"var(--token-c7b05702-f4f7-4d3f-be76-7f336e408407, rgb(224, 224, 224))",
									boxShadow:
										"0px 1px 0px 0px var(--token-325dbb34-3704-4fe8-9b79-64c8d834b7a6, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-wyJxC.framer-w0cqdt, .framer-wyJxC .framer-w0cqdt { display: block; }",
	".framer-wyJxC.framer-1yisz4f { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 75px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1120px; }",
	".framer-wyJxC .framer-1s47ypg { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px 30px 24px 30px; position: relative; width: 100%; }",
	".framer-wyJxC .framer-12byxbu-container, .framer-wyJxC .framer-1v4tmp3-container, .framer-wyJxC .framer-gp8xkx-container, .framer-wyJxC .framer-1oc305r-container, .framer-wyJxC .framer-42fto3-container, .framer-wyJxC .framer-18jmqxk-container, .framer-wyJxC .framer-1etrq84-container, .framer-wyJxC .framer-1uo6f59-container, .framer-wyJxC .framer-iln9ja-container, .framer-wyJxC .framer-cer9h4-container, .framer-wyJxC .framer-12dqk1c-container, .framer-wyJxC .framer-hfydsd-container, .framer-wyJxC .framer-wudjoc-container, .framer-wyJxC .framer-1oazxc-container, .framer-wyJxC .framer-11g1lyv-container, .framer-wyJxC .framer-n27hbi-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-wyJxC .framer-13fh5ot { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-wyJxC .framer-181m3s4 { align-content: center; align-items: center; aspect-ratio: 1.3333333333333333 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 24px); justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 32px; will-change: var(--framer-will-change-override, transform); }",
	".framer-wyJxC .framer-ks72dj { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 22px); position: relative; width: 22px; }",
	".framer-wyJxC .framer-17omepw, .framer-wyJxC .framer-1n6oe0w, .framer-wyJxC .framer-1n6i4m0, .framer-wyJxC .framer-vdragp, .framer-wyJxC .framer-105aogb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-wyJxC .framer-19y1uoe, .framer-wyJxC .framer-qackod, .framer-wyJxC .framer-x69vqi, .framer-wyJxC .framer-10oukxz, .framer-wyJxC .framer-1j1rklo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px 30px 20px 30px; position: relative; width: 342px; }",
	".framer-wyJxC .framer-gdyjey, .framer-wyJxC .framer-1jmmx7t, .framer-wyJxC .framer-qbpfeo, .framer-wyJxC .framer-1rfnokh, .framer-wyJxC .framer-yapi9k { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-wyJxC .framer-2fj8nq, .framer-wyJxC .framer-10gbgn0, .framer-wyJxC .framer-qrizvl, .framer-wyJxC .framer-ta4s95, .framer-wyJxC .framer-1i9uevj { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-wyJxC .framer-qp12jt, .framer-wyJxC .framer-1jp98bf, .framer-wyJxC .framer-1l2pheh, .framer-wyJxC .framer-yix7h8, .framer-wyJxC .framer-1pno2ad, .framer-wyJxC .framer-1yzxcde, .framer-wyJxC .framer-1rw4s64, .framer-wyJxC .framer-qixe0h, .framer-wyJxC .framer-f5qts4, .framer-wyJxC .framer-15iw5xz, .framer-wyJxC .framer-1d5twln, .framer-wyJxC .framer-6k4477, .framer-wyJxC .framer-lxlj5f, .framer-wyJxC .framer-1qaace8, .framer-wyJxC .framer-1jmjh16 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: 66px; justify-content: center; overflow: visible; padding: 20px 30px 20px 30px; position: relative; width: 1px; }",
	".framer-wyJxC .framer-1hjzuti, .framer-wyJxC .framer-b3s765, .framer-wyJxC .framer-icbhoy, .framer-wyJxC .framer-1qvc6g4, .framer-wyJxC .framer-fwauws, .framer-wyJxC .framer-1qphyvy, .framer-wyJxC .framer-1g27d52, .framer-wyJxC .framer-1kqsuv, .framer-wyJxC .framer-1dbzu6h, .framer-wyJxC .framer-109n1ir { bottom: 0px; flex: none; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 0px; width: 1px; z-index: 1; }",
	".framer-wyJxC .framer-h8von7, .framer-wyJxC .framer-n8qney, .framer-wyJxC .framer-n797kq, .framer-wyJxC .framer-w1q08y, .framer-wyJxC .framer-113cqfu { bottom: 0px; flex: none; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; width: 1px; z-index: 1; }",
	".framer-wyJxC .framer-q540yk, .framer-wyJxC .framer-12qhe31, .framer-wyJxC .framer-xc9s23, .framer-wyJxC .framer-11514mp, .framer-wyJxC .framer-1b1clqo { flex: none; height: 1px; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-wyJxC.framer-v-712fq6.framer-1yisz4f { height: min-content; }",
	...css2,
	...css,
];
var FramerAq87HMUf_ = withCSS(Component, css3, "framer-wyJxC");
var stdin_default5 = FramerAq87HMUf_;
FramerAq87HMUf_.displayName = "Helper/Pricing/Tab-1";
FramerAq87HMUf_.defaultProps = {
	height: 75,
	width: 1120,
};
addPropertyControls(FramerAq87HMUf_, {
	variant: {
		options: ["yaH3MSkbn", "XXYH9pKW3"],
		optionTitles: ["In-Active", "Active"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerAq87HMUf_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...HelperIconContainerFonts,
		...ArrowSquareRightFonts,
		...HelperYesNoFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:helper/pricing/tab-1
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "XXYH9pKW3",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Tab1FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"290dfde5ba1ea706d60e2fc238352b1d009206cc8b9cd5be32a648bae5cf9c7d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var tab_1_default = ComponentWithRoot;
export { tab_1_default as default };
